### ISSUE TITLE
Dataholder Admin api specs do not mention bearer token requirement

### ISSUE THREAD

**Issue by Kauabunga** [cdr-register/register#102]
[Dataholder Admin api specifications](https://consumerdatastandardsaustralia.github.io/standards/#admin-apis) do not specify any authentication required on the metrics and update endpoints.

This seems to conflict with the [Client Authentication documentation](https://consumerdatastandardsaustralia.github.io/standards/#client-authentication) mentioning the required Bearer Token

> Data Holders and Data Recipients MUST support the authentication of the CDR Register using a signed JWT according to the following requirements:

**Comment by CDR-Register-Stream** [comment]
@Kauabunga thanks for your query.

The requirements on the Admin API are owned by the Consumer Data Standards. Can you please raise this on the [standards-maintenance repo](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance)?

**Comment by CDR-Register-Stream** [comment]
Closing as response provided
