### ISSUE TITLE
Availability of openid scope in CDR SSA

### ISSUE THREAD

**Issue by imesh94** [cdr-register/register#106]
Originally posted at https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/208

# Request For Clarification
In the sample SSA given at https://cdr-register.github.io/register/#dynamic-client-registration, the openid scope is not present. But it can be seen in the provided sample response at https://cdr-register.github.io/register/#registration-response

Can you please clarify if we can expect the openid scope to be available in the SSA, or should it be manually added to the response by the data holder?

**Comment by imesh94** [comment]
kind reminder

**Comment by CDR-Register-Stream** [comment]
@imesh94 Thankyou for your query. This appears to be an oversight and for completeness should be included. We will look at addressing this in a future iteration of the Register design and will keep this ticket open to track.

In the meantime, you will need to manually add the scope in the response by the data holder.

**Comment by CDR-Register-Stream** [comment]
This issue is currently associated with Project 1.3, targeting completion by November 2020.

We are seeking feedback from the community on where this issue sits in terms of priority and the potential impact for deferring addressing this until 2021.

Feedback has been requested in this and other forums and will be considered until 1st August 2020

**Comment by commbankoss** [comment]
Commonwealth Bank is supportive of the inclusion of openid scope in CDR SSA, and sees minimal impact to us.

**Comment by WestpacOpenBanking** [comment]
Westpac has currently implemented in line with this recommendation. We are supportive of including this issue in the March v1.3.0 release.

**Comment by CDR-Register-Stream** [comment]
We are extending the request for feedback until **6th September** to give collaborators greater opportunity to contribute

**Comment by CDR-Register-Stream** [comment]
`openid` has now been added as a scope in the SSA.

Please refer to the [Dynamic Client Registration](https://cdr-register.github.io/register/#dynamic-client-registration) section of the CDR Register design for details

Closing as issue now addressed in V1.3.0 of the CDR Register design
