### ISSUE TITLE
Feedback 11 - Participant Statuses

### ISSUE THREAD

**Issue by acccivan** [cdr-register/register#11]
This thread has been created to allow for feedback on Participant Statuses within the CDR Ecosystem.

Details can be found at: https://cdr-register.github.io/register/#participant-statuses

All feedback is welcome.

**Comment by perlboy** [comment]
These look business orientated so make sense at the participant level although how do this pass into accreditation levels? It seems there could be multiple active statuses prior to hard suspension etc. Ie. A holder and/or a recipient could be technically non-conformant but be "in good standing" as a participant....

**Comment by spikejump** [comment]
It seems there are two levels of status: organisation and products.  I could have missed it in the [exposure draft ](https://www.accc.gov.au/system/files/Exposure%20draft%20CDR%20rules%2029%20March%202019.pdf).  But the draft only contained rules on accreditation of an organisation and nothing about accreditation of individual products.  Can there be a reference to the rules added to explain how individual products are accredited?

Does this imply it's possible that an organisation may be accredited but has no products that are accredited?
Assuming if a product is accredited then it automatically means the organisation is accredited?
What may be a reason that one product is accredited with Active status and another is with Suspended status?

The Data Holder is supposed to check the status of a request from an ADR.  What information is in the request that allows the Holder to validate the status of an individual product of an ADR?  Can there be clarifications added?  Preferably with detailed examples please.

In the case of an ADR having multiple accredited products, the ADR may chose to implement a common data layer for all its products and having only the data layer to access data from Data Holders.  In this case, is it the data layer that needs to be accredited and so it has its own certificate and status?

There's confusion over the product status.  Section "Software Product Status Changes" mentions 'active', 'suspended', 'revoked', 'surrendered' but the Schema section for 'RegisterProduct' has productAccreditationStatus with status of 'DRAFT', 'APPROVED', 'ACTIVE', 'INACTIVE'.

On behalf of Intuit.
Thanks.

**Comment by CDR-Register-Stream** [comment]
Thanks for all the feedback.
This is an old thread that I'll close, but with added references for those who stumble across it.

ADRs have accreditation statuses while Software Products have their own set of statuses. 

Details of these statuses, how they change and the responsibilities of Data Holders for these statuses are outlined [here](https://cdr-register.github.io/register/#accredited-data-recipient-and-software-product-statuses)

The swagger definition incorporating these statuses is available on the [CDR Register Design Schema](https://cdr-register.github.io/register/#schemas)
