### ISSUE TITLE
Register Swagger definition would benefit from documenting the infosec endpoints

### ISSUE THREAD

**Issue by CDR-Register-Stream** [cdr-register/register#110]
Currently the Register swagger definitions only document the APIs which map directly to the Register use cases, but the associated infosec endpoints are not included.

Additional swagger documentation can cover:
1. OIDC Discovery configuration endpoint 
2. Token endpoint
3. JWKS endpoints

Current swagger definitions can be found at:
[Register Swagger JSON](https://cdr-register.github.io/register/includes/swagger/swagger.json)
[Register Swagger YAML](https://cdr-register.github.io/register/includes/swagger/swagger.yaml)

**Comment by CDR-Register-Stream** [comment]
This issue is currently associated with Project 1.3, targeting completion by November 2020.

We are seeking feedback from the community on where this issue sits in terms of priority and the potential impact for deferring addressing this until 2021.

Feedback has been requested in this and other forums and will be considered until 1st August 2020

**Comment by WestpacOpenBanking** [comment]
Westpac is supportive of the creation of additional swagger definition covering the items listed.

**Comment by anzbankau** [comment]
ANZ agrees this will be a helpful addition to the standards.

**Comment by CDR-Register-Stream** [comment]
We are extending the request for feedback until **6th September** to give collaborators greater opportunity to contribute

**Comment by perlboy** [comment]
Just an FYI that it is not possible to accurately describe some of these endpoints in swagger on account of OpenID's use of space separated strings for arrays (they will have to go in as plain old string definitions).

**Comment by CDR-Register-Stream** [comment]
Thanks all for the feedback provided.

To move this issue forward, the following production endpoints and their locations will be documented:

| Endpoint  | Location |
| ------------- | ------------- |
| OpenID Provider Configuration End Point | https://api.cdr.gov.au/idp/.well-known/openid-configuration  |
| Token End Point  | Refer to contents of the openid-configuration endpoint |
| JSON Web Key Set End Point (Token)  | Refer to contents of the openid-configuration endpoint |
| JSON Web Key Set End Point (SSA  | https://api.cdr.gov.au/cdr-register/v1/jwks |

Note that the JSON Web Key Set End Point (SSA) lies outside of the OIDC configuration endpoint so is not currently specified there.

We will endeavour to document these within Swagger, noting that there may be technical constraints in achieving this (thanks @perlboy )

**Comment by CDR-Register-Stream** [comment]
OpenID Provider Configuration Endpoint and CDR Register JWKS endpoint have now been specified in the Swagger definition.

The JWKS Token endpoint has not been specified as it is not consumed by any of the CDR Register clients.

The token endpoint will not be specified at this stage

**Comment by CDR-Register-Stream** [comment]
Closing as complete
