### ISSUE TITLE
Seeking Clarification on Data Holder Responsibilities and consent management

### ISSUE THREAD

**Issue by andrewclatham** [cdr-register/register#114]
In reference to the Data Holder Responsibilities (https://cdr-register.github.io/register/#data-holder-responsibilities) I would like to obtain some further clarification regarding the responsibilities. 

The clarification is being sought primarily to understand the customer experience when an ADR/SP is inactive as to whether the existing consents are revoked and need to be re-authorised if the ADR/SP becomes Active again. Or, it is the Suspended/Removed status that triggers the revocation of all consents associated with the ADR/SP.

- Disclose of CDR Data
An ADR/SP holding a valid token, and the DH has an associated active consent, the DH will return appropriate CDR data via Bank APIs aligned to the authorised scopes.

- Facilitate Consent Authorisation
An ADR/SP, with the customer's consent, who has authenticated to the DH with their OTP, is able to receive a valid token containing the appropriate scopes as authorised by the customer.

- Facilitate Consent Withdrawal
An ADR/SP, with a valid token, is able to revoke a consent associated with the refresh token (V1.2) or cdr_arangement_id (v1.3).  i.e. The ADR can't access CDR data, and can't obtain new consents but can revoke the consent.<br>
Is there an intent here that when/if an ADR status is reinstated to Active that the existing consents that have not expired can still be used or all customers will need to re-consent for that ADR/SP?

- Consents Expire
The DH will allow consents to exist as-is and will expire "naturally" as per the timeframe authorised by the customer. Or for all intents and purposes all associated consents are to be immediately revoked?

- Cleanup Registration
The DH deletes or disables the ADR/SP record at the DH such that it can not be re-activated or reused but must complete the registration process again.

**Comment by bmangalaganesh** [comment]
@andrewclatham Does this [thread](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/217) help ?

Here is my understanding on things for the various scenarios you have described here

> Disclose of CDR Data
> An ADR/SP holding a valid token, and the DH has an associated active consent, the DH will return appropriate CDR data via Bank APIs aligned to the authorised scopes.

**Valid access token, Consent is current, DH should return CDR data**

> Facilitate Consent Authorisation
> An ADR/SP, with the customer's consent, who has authenticated to the DH with their OTP, is able to receive a valid token containing the appropriate scopes as authorised by the customer.

**The consent flow would return an ID Token, Access Token and refresh token to the ADR/SP


> Facilitate Consent Withdrawal
> An ADR/SP, with a valid token, is able to revoke a consent associated with the refresh token (V1.2) or cdr_arangement_id (v1.3). i.e. The ADR can't access CDR data, and can't obtain new consents but can revoke the consent.

**Not able to understand this question.
If the Consent is valid and the ADR/SP has a valid token they can access CDR Data. In this scenario, they can certainly revoke the existing consent.

> Is there an intent here that when/if an ADR status is reinstated to Active that the existing consents that have not expired can still be used or all customers will need to re-consent for that ADR/SP?

**The ADR status change to _inactive_ can occur in different scenarios (The software product is suspended or The software product has been surrendered or revoked) depends on how the status became. 

If the SP was revoked then the consents are automatically revoked. They would need customers to re-consent before getting access to the CDR data**

> Consents Expire
> The DH will allow consents to exist as-is and will expire "naturally" as per the timeframe authorised by the customer. Or for all intents and purposes all associated consents are to be immediately revoked?

**Not able to understand this question.
If the consent elapses on a datetime, they elapse. Any request after the consent expires will be rejected by the DH**


> Cleanup Registration
> The DH deletes or disables the ADR/SP record at the DH such that it can not be re-activated or reused but must complete the registration process again.

**This is not part of the CDR scheme. The scheme does not talk about DH doing things on their own. The DH will likely have to report to ACCC if they do something like this on their own which would result in CDR requests from ADR being declined. The reporting rules expect the DH to provide all CDR requests that they have declined at their end.

**Comment by andrewclatham** [comment]
Thank you @bmangalaganesh. That reference to the thread was perfect. Thank you.
