### ISSUE TITLE
Request for Clarification on refusal to disclose notification requirement

### ISSUE THREAD

**Issue by commbankoss** [cdr-register/register#115]
Commonwealth Bank is seeking clarification on the scenario where a DH refuses to disclose data to a DR. The register standards say, under section "Incident Management", that **"Reliance on this exemption is to be notified to the ACCC within 24 hours"**. Rules 4.7(3) details the need to notify the accredited person of a refusal to disclose, while rules 9.3 and 9.4 detail the record keeping and reporting requirements, neither of which mention this 24 hours reporting requirement to the ACCC.

Could @CDR-Register-Stream please clarify where in the rules (or elsewhere) this requirement is derived from?

**Comment by CDR-Register-Stream** [comment]
@commbankoss Thank you for your query.

I can confirm that the documentation is indeed out of date and the notification **to the ACCC within 24 hours** is an out of date statement.

I will update this issue to provide reference to the specific rules that are relevant for refusal to disclose.

Please watch this space

**Comment by CDR-Register-Stream** [comment]
Corrections to this documentation are now complete.

The [incident management section](https://cdr-register.github.io/register/#incident-management) has now been updated, removing reference to the draft rules and adding links to the published rules and associated amending instrument

Closing as complete
