### ISSUE TITLE
Communication security

### ISSUE THREAD

**Issue by WestpacOpenBanking** [cdr-register/register#12]
We are keen to understand how communication between participants and the register is secured.

We assume that:
 
* Register discovery APIs will be secured using TLS-MA with a register issued client certificate and access token where: 
    * Access tokens (and possibly refresh tokens) are to be initially obtained from the register’s identity provider using a `client_credentials` grant with the request format as `private_key_jwt` as [detailed](https://consumerdatastandardsaustralia.github.io/standards/#client-authentication) in the information security profile.
    * The [mandatory claims and parameters](https://consumerdatastandardsaustralia.github.io/standards/#private_key_jwt) in this request JWT would be provided by the ACCC.
    * The request JWT would contain the participant’s `client_id` as assigned by the register and would be signed using the private key associated with the client certificate. We are also keen to understand if refresh tokens would be issued during this process. 
    * The client certificate is different to the one issued for communication between data holders and data recipients. All certificates would be signed by the register certificate authority.
* Register forced cache refresh via the [POST /admin/registry/metadata](https://consumerdatastandardsaustralia.github.io/standards/#metadata-update) endpoint will be secured using TLS-MA using with a register issued client certificate. Prior to this, the register must authenticate using the `private_key_jwt` authentication method as in [section 9](https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication) of OIDC.

**Comment by CDR-Register-Stream** [comment]
Thanks for raising this issue.
This is an old thread that I'll close, but with added references for those who stumble across it.

* The [security profile](https://cdr-register.github.io/register/#security-profile) for the CDR Register, based off of the[ Consumer Data Standards Security Profile](https://consumerdatastandardsaustralia.github.io/standards/#security-profile)
* The [documentation ](https://cdr-register.github.io/register/#client-registration)for Dynamic Client Registration
* The [swagger definitions](https://cdr-register.github.io/register/#dcr-api) for Dynamic Client Registration
