### ISSUE TITLE
Clarification on Data Holder Brands

### ISSUE THREAD

**Issue by jakubvozarik** [cdr-register/register#124]
Hi,

What is the expectation in terms of CDR Register onboarding for Data Holders who issue white-label products under non-owned brands? Should these brands be registered under the data holder (white labeller) entity or should these be registered as separate entities?

Thank you

**Comment by CDR-Register-Stream** [comment]
@jakubvozarik Thank you for your query. I am consulting with the Rules team to provide feedback here.

Please stay tuned.

**Comment by jakubvozarik** [comment]
> @jakubvozarik Thank you for your query. I am consulting with the Rules team to provide feedback here.
> 
> Please stay tuned.

Thank you @CDR-Register-Stream 

Just to  expand a bit more on the context - the way we currently see it is that a Data Holder Entity (Bank A) would register a Data Holder Brand A (Bank A brand), Data Holder Brand B (Airline Brand), Data Holder Brand C (Supermarket Brand) for their white label products. As each of these brands could come with their own online banking experience and  digital identity, the customer experience would be mirrored in the consent/authorisation flow, whereby a customer would be selecting a Brand from which they want their data to be shared and authorisation would follow the experience which is known to the customer from their online banking experience. These individual brands would come with their own unique branded endpoints too. Consent would then be established with each brand separately, i.e. if a customer wants to share data for Supermarket and Airline brands, they would go through the consent/authorisation flow twice.
 
Would be great if we could get some feedback on this train of thought.

**Comment by nils-work** [comment]
Hi @jakubvozarik 
Not sure if [issue 187 on standards maintenance](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/187) has some information that may help for your situation?
How an entity is presented [here for example](https://www.cdr.gov.au/find-a-provider) may also be a factor as you mentioned, in relation to branding.

**Comment by nils-work** [comment]
Hi @jakubvozarik 

Combined with my comment above and related to your statement that 'individual brands would come with their own unique branded endpoints', there is also [this detail in the registry](https://cdr-register.github.io/register/#participant-endpoints) -

> Participants will be required to register base URIs to facilitate the implementation of the Consumer Data Standards

I hope that's helpful.

**Comment by jakubvozarik** [comment]
Thanks for your comments @nils-work 

 @CDR-Register-Stream  - was just wondering if you have any further guidance on this, as we need to know how to register and onboard onto CDR Register with multiple brands.

Further to that we would like to know how a DH can stipulate a different base URI for unauthenticated endpoints?
From the Standards:

Holder Path: The holder path is a base path set by the data holder. It can be any URI desired by the holder. **While all authenticated end points must be accessible under the same holder path the data holder may stipulate a different holder path for unauthenticated end points.**

**Comment by jakubvozarik** [comment]
Hi @CDR-Register-Stream 

I would like to follow up again to see whether there is any further guidance on how to onboard onto CDR register with multiple brands and also check whether a DH can have multiple brands with the same DNS?

Thanks

**Comment by CDR-Register-Stream** [comment]
Hi @jakubvozarik thanks for your query. The [on-boarding guide](https://www.accc.gov.au/focus-areas/consumer-data-right-cdr-0/on-boarding-guide) details how multiple brands are configured on the CDR Register.
There are currently no constraints preventing the same domain to be used across multiple brand endpoints. It is left to the Data Holder to ensure they are meeting the requirements of the CDS when configuring.

A good example to consider is brand specific GetMetrics collection. CDS Decision Proposal [145](https://github.com/ConsumerDataStandardsAustralia/standards/issues/145) introduces the concepts of brand aware metrics collection. Therefore, based on this outcome, you mayneed to ensure your brands are configured correctly to satisfy this requirement. If required, brand specific [AdminBaseUri endpoints](https://cdr-register.github.io/register/#participant-endpoints) would need to be defined in the Register to cater for brand specific metrics collection but path rather than domain could be used to differentiate between brands.

**Comment by CDR-Register-Stream** [comment]
@jakubvozarik @nils-work After discussions on Wednesday, I note that the above comment doesn't outline the whitelabel scenario. We are working to get confirmation with C&E on what the position is here. 

Please stay tuned.

**Comment by CDR-Register-Stream** [comment]
@jakubvozarik @nils-work. 

We now have the following statement from the compliance and enforcement team:

_Metrics collection by the CDR Register will be measuring how brands perform within the Consumer Data Right ecosystem irrespective of their white label relationship. Therefore, white-label service providers will need to provide separate GetMetrics endpoints for all brands they service._

**Comment by nils-work** [comment]
Hi @jakubvozarik 
There is some [more detail about brands here](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/264#issuecomment-789333270).

**Comment by CDR-Register-Stream** [comment]
We have published technical commentary on white labelling to compliment [noting paper 169](https://github.com/ConsumerDataStandardsAustralia/standards/issues/169).

Please take a look at the article [White Labelled Brands in the CDR](https://cdr-support.zendesk.com/hc/en-us/articles/900003938166-White-Labelled-brands-in-the-CDR)

**Comment by CDR-Register-Stream** [comment]
Closing as complete
