### ISSUE TITLE
Modify Registration

### ISSUE THREAD

**Issue by eligizim** [cdr-register/register#125]
Hi there,
when DR requests to modify the exsiting registration with DH, should DH invalidate all the consents for that client? if not, what is the scope of the changes that DR can make to their sotware and update the SSA with CDR? how do we make sure that customer is still ok with the initially provided consent to the software considering that it has changed?

**Comment by CDR-Register-Stream** [comment]
@eligizim Thanks for your query. Please take a look at the [Client Registration fields](https://cdr-register.github.io/register/#dynamic-client-registration) and what is modifiable.

I believe the scenario you have highlighted is the change in authorisation scopes. Currently the CDR Register assigns the authorisation scopes when generating the SSA. Currently all authorisation scopes defined in the [CDS](https://consumerdatastandardsaustralia.github.io/standards/#authorisation-scopes) are assigned.

In the future however, this may not be the case. We will need to provide guidelines on what consents are still relevant and which should be invalidated. This is a future piece of work and thanks for highlighting the considerations which need to be made.

Please let me know if you require any further details.

**Comment by CDR-Register-Stream** [comment]
Closing as response has been provided
