### ISSUE TITLE
Versioning of the GetSoftwareStatementAssertion and GetDataRecipients endpoints

### ISSUE THREAD

**Issue by CDR-Register-Stream** [cdr-register/register#127]
To align with the Register requirements to cater for the CDR Arrangement Management Endpoint (#116) the [SSA definition](https://cdr-register.github.io/register/#dynamic-client-registration) is being updated. Although this doesn't affect the swagger definition for the [GetSoftwareStatementAssertion API](https://cdr-register.github.io/register/#getsoftwarestatementassertion-ssa), it does impact the decoded payload.

Therefore, we will be incrementing the x-version value for this API (Initial will be 1, subsequent will be 2 ).

It has been highlighted that the Data Holder does not have an explicit way to determine the version of the SSA it is receiving.
Therefore, a version claim should be added to the SSA definition so that it can be handled accordingly

**Comment by CDR-Register-Stream** [comment]
To elaborate on the above requirement of the version claim.
For completeness, it is being proposed that the version claim will be added to the SSA definition so that the DH has the ability to explicitly check which version of the SSA is being supplied.

We will NOT be mandating that this claim is used, simply providing the mechanism for completeness. It will be up to the DH to determine whether this adds value to their SSA processing logic.

**Comment by WestpacOpenBanking** [comment]
Westpac does not recommend the inclusion of a versioning claim as it adds unnecessary complexity with no clear benefit. In particular, RFC7591 [instructs that](https://tools.ietf.org/html/rfc7591#section-2) servers MUST ignore any client metadata (including those provided as claims in a software statement) sent by the client that it does not understand. Therefore, if any new claims placed in the SSA are not recognised by the server, then they should not be played back in the response and the recipient should treat the value as not being applied by the authorisation server. The effect of these statements is that SSAs are meant to be always backwards compatible and hence there is no need for explicit versioning. Although it has been clarified that the claim need not be used by data holders, including it would require implementation effort and add ongoing complexity for all parties.

**Comment by CDR-Register-Stream** [comment]
@WestpacOpenBanking Thank you for your input on this issue.

I note that this model parallels to that of the OIDC Configuration Endpoint versioning discussion we covered in issue #55. This issue identified no need for the ADR to know which version of the OIDC Configuration endpoint it was consuming.

Therefore, to summarise the result of this issue:
1. We will not include the version claim in the SSA.
2. The following x-version fields will apply to the APIs:



API | Versions available Pre-Nov 2020 | Versions available Post Nov 2020
-- | -- | --
GetDataHolderBrands | 1 | 1
GetSoftwareStatementAssertion | 1 | 1,2
GetSoftwareProductsStatus | 1 | 1
GetDataRecipientsStatus | 1 | 1
GetDataRecipients | 1 | 1,2

**Comment by spikejump** [comment]
@CDR-Register-Stream Please clarify whether this x-version is the same as what's [mentioned here ](https://github.com/cdr-register/register/issues/69#issuecomment-652110941) and latest 1.2 spec as x-v?  Assume it is a typo here on x-version?  or has x-v being removed and x-version will be used in a future version?

**Comment by CDR-Register-Stream** [comment]
@spikejump thanks for your query. 

The updates to [1.2.2](https://cdr-register.github.io/register/includes/releasenotes/releasenotes.1.2.2.html#register-apis) includes updating the Register Swagger definitions to include the `x-version` field, per api, which had been missing.

The `x-v` header is used to specify which `x-version` of the API is to be returned as per the [CDS HTTP Headers section](https://consumerdatastandardsaustralia.github.io/standards/#http-headers).

Issue #69 talks to returning the `x-v` header in the response, which will still remain.

Please let me know if you require any further information

**Comment by spikejump** [comment]
Thanks for clarifying @CDR-Register-Stream

**Comment by CDR-Register-Stream** [comment]
Closing as complete.
 
All versioning information has been captured in 1.2.x releases of the CDR Register design and is marked complete as of [1.2.2](https://cdr-register.github.io/register/includes/releasenotes/releasenotes.1.2.2.html#register-apis)
