### ISSUE TITLE
CDR Register Swagger Questions

### ISSUE THREAD

**Issue by alan-elabor8** [cdr-register/register#128]
Hi,

I have some queries on the CDR Register Swagger document: [https://github.com/cdr-register/register/blob/master/includes/swagger/swagger.json]

Can you please clarify if the following types in the Swagger should have `links` and `meta` elements?

**ResponseRegisterDataRecipientList**
This type lists links and meta as required but links and meta are not included in the properties element.

```
"ResponseRegisterDataRecipientList": {
      "description": "Response containing a list of Data Recipients in the CDR Register",
      "required": [
        "data",
        "links",
        "meta"
      ],
      "type": "object",
      "properties": {
        "data": {
          "description": "Response data for the query",
          "uniqueItems": false,
          "type": "array",
          "items": {
            "$ref": "#/definitions/RegisterDataRecipient"
          }
        }
      }
    }
```

**DataRecipientsStatusList**
This type does not include links or meta. Is that correct? No pagination for “/{industry}/data-recipients/status” ?

**SoftwareProductsStatusList**
This type does not include links or meta. Is that correct? No pagination for "/{industry}/data-recipients/brands/software-products/status"

Many thanks
Alan

**Comment by CDR-Register-Stream** [comment]
@alan-elabor8 Thank you for your query.

The required fields are extraneous and will be formally removed as they conflict with the actual fields defined in the schema.
However, the intent is that the payloads returned by the APIs conform to the[ CDS payload conventions specification](https://consumerdatastandardsaustralia.github.io/standards/#payload-conventions). 

Conformance to CDS payload conventions will be addressed in a future release and is being tracked [here](https://github.com/cdr-register/register/issues/122).


Please let me know if you require further details

**Comment by CDR-Register-Stream** [comment]
Tracking in #122 so closing here
