### ISSUE TITLE
Clarification on Data Recipient, Software Product Status Check and DCR SSA Org Id, Software Id

### ISSUE THREAD

**Issue by Randima-ibm** [cdr-register/register#132]
As part of Request for Disclosure of CDR Data, DH required to check the Validity of Accredited Data Recipient and associated Software Product Status per https://cdr-register.github.io/register/#metadata-cache-management section: Checking Request Validity.
Note: Status is available at all 3 levels (Legal Entity, Brand and SW product)
As per the DCR process, Org Id (ADR Brand Id)  and Software Id is available to DH part of SSA, but not the Legal Entity Id/Data Recipient Id. I am wondering from where the DH derive the dataRecipientId of the ADR to query the Metadata Cache for ADR Status?

![image](https://user-images.githubusercontent.com/53943968/90016935-1de38a80-dcee-11ea-8a7e-a51feb13239d.png)

Are the DH expected to derive the dataRecipientId (equivalent to the legalEntityId) from the Brand to Data Recipient relationship? 

During the DCR process, to register the Software Product with a DH, the ADR sends an HTTP POST registration request to the DH registration endpoint containing the JWT which contains the SSA. This SSA contains the  Org_id (ADR Brand Id) and Software Id, but not the Legal Entity Id/Data Recipient Id. Any reason why Legal Entity Id (Data Recipient Id) intentionally left out in SSA?
The same concern seemed to have raised by @jakubvozarik in the comment https://github.com/cdr-register/register/issues/31#issuecomment-613423577
Can @CDR-Register-Stream kindly clarify this as even with the updated documentation, question still remains. Thanks

![image](https://user-images.githubusercontent.com/53943968/90017008-394e9580-dcee-11ea-9e73-ddb2bf7402cc.png)

**Comment by CDR-Register-Stream** [comment]
@Randima-ibm Thank you for your query. 

Data Holders can retrieve the Data Recipient model from the [GetDataRecipients API](https://cdr-register.github.io/register/#getdatarecipients). 
This API provides the entire hierarchy of the Data Recipient from Legal Entity to Brand to Software Product. 
The expectation is that Data Holders would retrieve the entire hierachy and store this in their [Metadata Cache](https://cdr-register.github.io/register/#ecosystem-component-diagram). 

Data Holders are expected to then use the [Status APIs](https://cdr-register.github.io/register/#getsoftwareproductsstatus) to keep this model up to date as per the [polling requirements](https://cdr-register.github.io/register/#metadata-cache-management).

So why is the legal entity left out of the DCR Request? Well the ADR is expected to register their software product against a Data Holder Brand. 
Currently, there hasn't been a need to add the actual legal entity to the DCR request as this can be inferred against the Data Holder Brand.

Perhaps we can ask another question here:

 _Is there value during the DCR process to provide context of the Data Recipient Legal Entity?_

**Comment by Randima-ibm** [comment]
@CDR-Register-Stream Thank you for the explanation. 
With regard to your question, 
_Is there value during the DCR process to provide context of the Data Recipient Legal Entity?_
We believe there is some value in having the Data Recipient Legal Entity in the DCR process, so that validity of the Data recipient status can be checked against the metadata cache without traversing through the hierarchy.

Further, during the run time Disclosure of CDR Data API call, we check the status of the ADR and SW product. Not the Brand status.

**Comment by CDR-Register-Stream** [comment]
@Randima-ibm  Issue #141 has been raised to track this change request.

Thank you for your input on this issue.

**Comment by CDR-Register-Stream** [comment]
Closing issue. Please refer to #141 to track this change request
