### ISSUE TITLE
The x-v request headers appear to not have the right description

### ISSUE THREAD

**Issue by pcurtisrab** [cdr-register/register#133]
Since 1.2.2, the [Register APIs](https://cdr-register.github.io/register/#getdataholderbrands) have an optional `x-v` header. The descriptions are:

> The [version](https://consumerdatastandardsaustralia.github.io/standards/#response-headers) of the API end point that the CDR Register has responded with.

Note that the linked description comes from the version headers. It seems more reasonable for the text to be related to the request, rather than the response. For example, from the standards:

> Version of the API end point requested by the client. Must be set to a positive integer. The holder should respond with the highest supported version between x-min-v and x-v. If the value of x-min-v is equal to or higher than the value of x-v then the x-min-v header should be treated as absent.
> If all versions requested are not supported then the holder must respond with a 406 Not Acceptable.

Assuming this is the intended copy, can I ask these followup questions:

1. Why is `x-v` not mandatory, and `x-min-v` not allowed?
2. Is it envisaged that `x-v` will remain optional for the foreseeable future?
3. Are the older versions of endpoints still supported in version 1.2 of the standards?
4. Are GetDataRecipientStatus and GetDataRecipients version 1 still available? If so, what is the expected behaviour when the `x-v` header parameter is not supplied? If not, what will be the behaviour when `x-v` of 1 is supplied when the published endpoint version is version 2?
5. Is there any general guidance offered on whether Data Recipient implementations should supply these version numbers, given that they are optional?

**Comment by pcurtisrab** [comment]
Pragmatic design decision to be adopted is to allow configuration via environment variable `ADR_GETSSA_XV`:
- If `false` or not supplied, `x-v` header will not be sent
- If a whole number greater than or equal to 1, will be supplied as `x-v` header.

This has been implemented in https://github.com/Regional-Australia-Bank/ADR-Gateway/commit/a23fb62406688e69afa60711f1c6aa0d516e1a05

**Comment by CDR-Register-Stream** [comment]
@pcurtisrab Thanks for your query and apologies the delay in giving this topic priority.

The swagger description for the x-v header is indeed poorly worded so it will be updated as part of the next swagger update.

In response to your questions,

> 1. Why is x-v not mandatory, and x-min-v not allowed?

Some history. The headers used in the CDR Register design do not currently align with the CDS, hence we are missing the x-min-v header. It is intended for the CDR Register APIs to align to the CDS [payload ](https://consumerdatastandardsaustralia.github.io/standards/#payload-conventions) and [header](https://consumerdatastandardsaustralia.github.io/standards/#http-headers) standards. 
We are tracking this work at  #122. Our future changes to align to the headers will be delivered at the same time as the payload conventions

> 2. Is it envisaged that x-v will remain optional for the foreseeable future?

As described in 1, we will align to the CDS, we just need to manage the change management risk. We will provide at least a 6 month lead time of any changes as per our process

> 3. Are the older versions of endpoints still supported in version 1.2 of the standards?

None of the Register APIs have yet been deprecated so previous APIs can still be called if appropriate

> 4. Are GetDataRecipientStatus and GetDataRecipients version 1 still available? If so, what is the expected behaviour when the x-v header parameter is not supplied? If not, what will be the behaviour when x-v of 1 is supplied when the published endpoint version is version 2?

As described in 3, older versions are still available

> 5. Is there any general guidance offered on whether Data Recipient implementations should supply these version numbers, given that they are optional?

The current behaviour is that the latest version of the API will be returned if no x-v header is provided. This will change when this header becomes mandatory


To make this more transparent, we will document an endpoint version schedule, aligned to the documentation approach made in the [CDS](https://consumerdatastandardsaustralia.github.io/standards/includes/endpoint-version-schedule/#endpoint-version-schedule). This will provide greater transparency on what versions of the APIs are available.

We will look at deprecation schedules in a future iteration.

**Comment by CDR-Register-Stream** [comment]
[V1.4.0](https://cdr-register.github.io/register) of the CDR Register design introduces updated to the swagger to correct X-V header descriptions.

Issue #175 has been raised to track documentation improvements to add an endpoint version schedule
