### ISSUE TITLE
ADR Logo - Domain and Format

### ISSUE THREAD

**Issue by LizLau** [cdr-register/register#134]
For CDR Implementation Meeting
1. What is the domain that we will receive for the logo URI? 
a. Will it only be an ACCC domain e.g., accc.gov.au OR
b. could it be any ADR domain?   

2. What kind of image file formats should we expect for the ADR Logo on the URL? (e.g. png, jpeg)
a. Is there a list of formats OR 
b. Is there only one  in particular format?

**Comment by CDR-Register-Stream** [comment]
@LizLau thank you for your query.

1. The CDR Register does not host the logo for any of the ADRs. The logo_uri is submitted to the Data Holder Brand via [Dynamic Client Registration](https://cdr-register.github.io/register/#dynamic-client-registration). This URI is defined by the ADR and is intended to point to a logo the ADR hosts.

2. There are currently no constraints on the file formats or image specifications provided on the logo uri. 
Previous discussion on this topic acknowledged that there is no specification that current participants align to. 
That said, there would be an expectation that participants choose file formats that are widely supported

Please let me know if you have any additional questions or comments.

**Comment by CDR-Register-Stream** [comment]
Closing as answered. If there are further questions, please raise a new issue
