### ISSUE TITLE
Customer request for data sharing arrangement

### ISSUE THREAD

**Issue by LizLau** [cdr-register/register#135]
Please note this question was logged in the minutes dated 13/8 - but has not been answered 
CDR allows a customer to request for data sharing arrangement information. Page 90 of the rules section 9.5 says 
"3) A request under this rule must be in the form (if any) approved by the commission for the purpose of this subrule" 
Q. Is this a physical form? If so, are ACCC going to provide an approved template or would you like each organisation to draft a form for approval? If the later, are there guidelines for how this process will work?

**Comment by CDR-Register-Stream** [comment]
@LizLau thank you for your query.

We have sought feedback from the rules team on this question and have the following response:

_The ACCC has not currently prescribed a form for the purposes of rule 9.5(3) or (4), and has left the format for making a request and responding to a request open. However, the ACCC is open to feedback if participants believe there is a need for the ACCC to consider prescribing forms for the purposes of rule 9.5. If you have any such feedback, feel free to send it to the ACCC-CDR mailbox: accc-cdr@accc.gov.au._

**Comment by CDR-Register-Stream** [comment]
Closing as answered. If there are further questions, please raise a new issue
