### ISSUE TITLE
Further clarification on the complaints process being on the CDR Policy

### ISSUE THREAD

**Issue by LizLau** [cdr-register/register#136]
For CDR Implementation Meeting
Hello, this question was logged in the minutes dated 13/8 but have not been answered. I think it's also referenced to the wrong # (i.e. 66 which relates to the data holders' logo)

Question relates to Part 7 – Rules relating to privacy safeguards, section 7.2.1.

According to this rule, we need to include details of the complaints process on the CDR policy. We are already required by RG165 to provide details of our complaints process online.

Just wanted to find out whether the following details need to be spelled out on the CDR policy OR whether we can refer customers to our generic complaints process that include the details below?
(6) In addition to the information referred to in paragraphs 56ED(4)(b) and (5)(d) of the Act, a CDR participant’s CDR policy must include the following information in relation to the participant’s internal dispute resolution processes:
(a) where a CDR consumer complaint can be made;
(b) how a CDR consumer complaint can be made;
(c) when a CDR consumer complaint can be made;
(d) when acknowledgement of a CDR consumer complaint can be expected;
(e) what information is required to be provided by the complainant;
(f) the participant’s process for handling CDR consumer complaints;
(g) time periods associated with various stages in the CDR consumer complaint process;
(h) options for redress;
(i) options for review, both internally (if available) and externally.

Note: This subrule is a civil penalty provision (see rule 9.8).

**Comment by robhale-rab** [comment]
You might find it helpful to have a look at the Regional Australia Bank CDR policy and how we handled this.  We are already an AFCA member so in a similar situation. Page 8 and 9 of this document might help you with some techniques you could use.
https://www.regionalaustraliabank.com.au/-/media/files/cdr-community-assets/cdr-policy-development/CDR-Policy-Compliance-XREF-Mapping---PDF-Document.pdf

**Comment by CDR-Register-Stream** [comment]
@LizLau Thank you for your query and @robhale-rab, appreciate your input.

This question has been answered on our Zendesk platform, where rules related questions are fielded.
Please refer to the following article: https://cdr-support.zendesk.com/hc/en-us/articles/900002644723

**Comment by CDR-Register-Stream** [comment]
Closing as answered. If there are further questions, please raise a new issue
