### ISSUE TITLE
Request to add Data Quality Email to RegisterDataHolderBrand

### ISSUE THREAD

**Issue by perlboy** [cdr-register/register#138]
The ACCC recently provided the DSB a response to a question on the [Standards Maintenance](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/231#issuecomment-641640740) repository.

Within this response the ACCC stated:
> Interested parties should make any complaints about data accuracy or how product reference data is being shared **directly** to the data holder.

While this **sounds** like a reasonable statement in reality every Holder is providing a variety of contact methods, often buried deep in FAQs or elsewhere in convoluted websites. This makes the production of automated error reports to individual holders very difficult and with known Holder endpoints already exceeding 20 adds a significant administrative burden on _"interested parties"_ to report data quality issues for which the ACCC has indicated should be shared directly with data holders.

Consequently, could the ACCC:
1) Introduce an `apiContactEmail` into the `RegisterDataHolderBrand` for the purposes of clearly identifying the appropriate contact address for API issues
2) Expose the `apiContactEmail`, or align the contact addresses listed at the [Find a Provider](https://www.cdr.gov.au/find-a-provider) page. For instance, CBA's email [listed there](https://www.cdr.gov.au/find-a-provider?provider=DHBNK000007) is `CBAOpenBanking@cba.com.au` while the API contact [address listed](https://www.commbank.com.au/developer) on CBA's site (at the very very bottom of the page) is `openbankingsupport@cba.com.au`.

**Comment by CDR-Register-Stream** [comment]
@perlboy Thanks for your query,

I have received the following input from C&E to help provide clarification

---

_If a data recipient has concerns about the quality of product data, they are welcome to raise those concerns with the data holder directly to seek a fix. However, as data quality is integral to the effective operation of the CDR, the ACCC will always be interested in issues of inaccurate or missing product data. Data recipients can report their concerns to the ACCC at [cdr.gov.au/contact-us](cdr.gov.au/contact-us)._ 

---

As for a Register of contact details, I will leave this issue open to track. I'll raise this issue internally to see how this maps to  intended processes

**Comment by nils-work** [comment]
Hi @CDR-Register-Stream, @perlboy 
There seems to be a [related comment here](https://github.com/cdr-register/register/issues/26#issuecomment-541976086) from Oct 2019

**Comment by perlboy** [comment]
@CDR-Register-Stream providing an answer to C&E:

> If a data recipient has concerns about the quality of product data, they are welcome to raise those concerns with the data holder directly to seek a fix. 

The whole point of this request was that it is not possible to automatically identify the contact address.

>However, as data quality is integral to the effective operation of the CDR, the ACCC will always be interested in issues of inaccurate or missing product data. Data recipients can report their concerns to the ACCC at cdr.gov.au/contact-us.

This form is tedious for automated compliance checking and there is a question regarding whether it's really recipients responsibility to provide effectively free consulting services to the ACCC regarding compliance to it's own rules.

**Comment by CDR-Register-Stream** [comment]
Thanks @perlboy and @nils-work for your comments.

I'm keen to address this in a generic way. We should be considering the following stakeholders:
1. Data Holders
2. Data Recipients
3. 3rd parties (e.g. vendors or data quality "observers")
4. ACCC

We already collect email addresses per participant and publish these on the public register. To anticipate a question from @perlboy, expectation on how these email addresses are to be used needs to be well defined and then the mechanism to automatically consume them can be defined.

I'm not sure if GetDataHolderBrands is a good fit here as it is only usable by data recipients. Other stakeholders cannot leverage this API.

We are working this internally and will then provide a response. Stay tuned

**Comment by perlboy** [comment]
As an FYI there is a (somewhat) related issue opened for publishing PRD endpoints in an API as well: https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/358

**Comment by CDR-Register-Stream** [comment]
We will continue to work this from an operational perspective and then provide technical changes to facilitate these operational requirements. However we will not couple this work to the July 2021 time frame.

This issue will be kept open to track ongoing work

**Comment by perlboy** [comment]
See https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/354

**Comment by CDR-Register-Stream** [comment]
At this stage, we’re NOT proposing a change on the [RegisterDataHolderBrand ](https://cdr-register.github.io/register/#tocSregisterdataholderbrand )schema to include a dedicated contact email address (or other contact method) for participants to reach the data holder for data quality issues specifically. 

Its noted that there’re 2 established processes for participants/non-participants for raising data quality concerns with the data holder , which have been highlighted below for reference. These are established operational processes with a dedicated operational support; and at this stage we are not prioritising an alternate process for raising data quality issues with data holders.  

•	CDR Service Management Portal: where the CDR Participant has an established access to the CDR Service Management Portal, the recommended approach would be to continue to use the portal for raising data quality issues with the data holder – while including “data quality” as the incident category. This allows for a centralized triage of the data quality issue, along with an established process for remediation prioritization with the concerned data holder. This process also supports an established escalation process with ACCC Compliance & Enforcement, where there’re concerns with the data holder’s handling of the issue.

•	ACCC Complaints Report - For non-CDR participants, who do not have an access to the CDR Service Management Portal, the recommended approach would be to use the ACCC / Complaints Report available on the [CDR Contact us page](https://www.cdr.gov.au/contact-us). 


Meanwhile, DSB is running a consultation exercise with the CDR community on establishing formal processes for identifying and managing problems relating to the quality of the data transmitted in CDR (Consumer Data Right) payload. Feedback period for the same has concluded recently. In the event that there’s a change planned on the above mentioned processes, a guideline would be shared with the community
