### ISSUE TITLE
Feedback 14 - Whitelisting Authorisation Scopes

### ISSUE THREAD

**Issue by CDR-Register-Stream** [cdr-register/register#14]
The standards define authorisation scopes required to access data available via each endpoint.
[Authorisation Scopes](https://consumerdatastandardsaustralia.github.io/standards/#authorisation-scopes)

Whitelisting would allow the anticipated authorisation scopes used by each product to be stored in the CDR Register. Data Holders can then map consent requests to these whitelisted authorisation scopes.

This could be a voluntary process.

The ACCC is requesting feedback from the community to identify use cases for this functionality.

**Comment by JamesMBligh** [comment]
With only a single accreditation tier then this would be opt-in only and there would be minimal incentives for recipients to opt-in.

Once multiple accreditation levels are introduced (as has been flagged will be the case) this could be an invaluable feature as it could give the ACCC low level control of what specific accreditation’s mean.

Maybe it would be a good to allow for a white list in the structure (ie. an array of scopes) but not requiring it (ie. if it is absent then no constraint applies).

**Comment by perlboy** [comment]
If the intention of the ACCC is to accredit individual products and maintain control over what those products are verified for then a list of valid scopes is mandatory. Once again, in a similar vein to my comment in #15, OIDC Federation has explicit support for assertions that contain a list of allowed scopes.

Finally, not designing something for a situation you know is coming is foolhardy. If all scopes are to be supported initially then list all of the scopes explicitly (not assume all if absent). This allows reduction of scopes as accreditation levels are introduced.

**Comment by commbankoss** [comment]
Commonwealth Bank supports the inclusion of whitelisting scopes for February. By registering which scopes are required to enable a product and use case, the regime would allow a data holder to verify with the customer the scopes being requested at the time of consent. This enhances the trust within the eco-system and ensures that customer consent is well informed and specific. Commonwealth Bank recommends including this option now, and moving to mandatory implementation in future.

**Comment by NationalAustraliaBank** [comment]
NAB strongly recommends the mandatory inclusion of white listed authorisation scopes for each software product.

This will allow the ACCC to monitor and control which software products will have access to CDR consumer data types and ensure it is in accordance with the software product's accredited purpose. This includes supporting any conditions that were imposed by the ACCC when the accreditation decision was made.

This will also enable Data Holders to validate the authorisation scopes within the request object of the authorisation flow, to prevent data recipients requesting for scopes which the software product does not have a valid purpose for.

This is supported in the client metadata under OAuth 2.0 Dynamic Registration as the `scope` field, defined as a _string containing a space-separated list of scope values that the client can use when requesting access tokens_.

This would also remove the need for a software product's `accessLevel` in the customised metadata.

**Comment by CDR-Register-Stream** [comment]
Thanks to all for their feedback.

The [dynamic client registration](https://cdr-register.github.io/register/#dynamic-client-registration) design caters for whitelisted authorisation scopes so this will be supported.

Closing as complete
