### ISSUE TITLE
Rules relating to Privacy Safeguard - Options for Redress

### ISSUE THREAD

**Issue by LizLau** [cdr-register/register#140]
For CDR Implementation Meeting
Please refer to Division 7.2. Rules Relating to Privacy Safeguards

Subdivision 7.2.1 Rules relating to consideration of CDR Data Privacy
7.2 Rules relating to privacy safeguard 1 - open and transparent management of CDR Data 
(6) In addition to the information referred to in paragraphs 56ED(4)(b) and (5)(d) of the Act, a CDR participant’s CDR policy must include the following information in relation to the participant’s internal dispute resolution processes:
                     (h)  options for redress

The nature of CDR lends itself to many and varied possible complaints, with various outcomes. On this basis would the ACCC have any concerns if our policy covered the requirement with the following wording:

_The possible resolutions available to you will depend on the nature of your complaint (for example, correcting any incorrect information held)._

**Comment by CDR-Register-Stream** [comment]
@LizLau. Thanks for your query.

This repository is dedicated to questions and collaboration regarding the design of the CDR Register. 
In the future, enquires outside of this scope and related to rules should be submitted to: https://cdr-support.zendesk.com/hc/en-us

In the meantime, the rules team have provided the following response to your query:

_For information and guidance on preparing and maintaining a CDR policy, the ACCC and Office of the Australian Information Commissioner (OAIC) encourages participants to review the [Guide to developing a CDR policy](https://www.oaic.gov.au/consumer-data-right/guidance-and-advice/guide-to-developing-a-cdr-policy/#information-about-the-consumer-complaints-process-for-data-holders-and-accredited-data-recipients) and the [CDR Privacy Safeguard Guidelines](https://www.oaic.gov.au/consumer-data-right/cdr-privacy-safeguard-guidelines/) both issued by the OAIC._

**Comment by CDR-Register-Stream** [comment]
Closing as answered. If there are further questions, please raise a new issue
