### ISSUE TITLE
Consider including the legal entity identifiers in the SSA definition

### ISSUE THREAD

**Issue by CDR-Register-Stream** [cdr-register/register#141]
Initially raised in #132 

Currently, the data holder is only able to obtain brand and software product Ids from the [SSA definition](https://cdr-register.github.io/register/#dynamic-client-registration). In order to identify the legal entity, for instance to check status, the DH is required to call [GetDataRecipients](https://cdr-register.github.io/register/#getdatarecipients), map the Brand ID and traverse the response to determine the legal entity ID.

This process would be streamlined if the value was included in the SSA.

**Comment by WestpacOpenBanking** [comment]
Westpac is supportive of this change.

**Comment by CDR-Register-Stream** [comment]
Incorporating this change would require the following:

* `legalEntityId` added as a new field in the SSA as an **optional** field
* [GetSoftwareStatementAssertion ](https://cdr-register.github.io/register/#getsoftwarestatementassertion-ssa) version would increment
* `legalEntityId`  would move to a **required** field in the future to cement its status as a first-class field

How Data Holders choose to handle the `legalEntityId` is dependent on their implementations and is not covered here. The key expectation is that Data Holders would not return an error if the field is present.

The intent of having the field as initially **optional** and moving it to **required** as a later date is to ease transition.

**Comment by CDR-Register-Stream** [comment]
`legal_entity_id` and `legal_entity_name` have now been added as an optional field in the SSA.

Please refer to the [Dynamic Client Registration](https://cdr-register.github.io/register/#dynamic-client-registration) section of the CDR Register design for details

Closing as issue now addressed in V1.3.0 of the CDR Register design
