### ISSUE TITLE
Base URI Values

### ISSUE THREAD

**Issue by perlboy** [cdr-register/register#143]
Can the register team confirm that the Base URI's used in [RegisterDataHolderBrandServiceEndpoint](https://cdr-register.github.io/register/#tocSregisterdataholderbrandserviceendpoint), specifically the `publicBaseUri`, `resourceBaseUri`, `extensionBaseUri` **do not** include the Standards specified component of `/cds-au/v1` ?

**Comment by CDR-Register-Stream** [comment]
@perlboy Thank you for your query.
The Base URIs you have specified do not include the standards specified components of `/cds-au/v1`.

As defined in the[ URI structure](https://consumerdatastandardsaustralia.github.io/standards/#uri-structure) section of the CDS, 

> The URI structure for API end points in the standards MUST be implemented as follows:
> ```<holder path> / cds-au / <version> / <industry> / <resource>```

The base uris represent the `<holder path>` component of the URI definition.

Please let me know if further clarification is required.

**Comment by perlboy** [comment]
Hi @CDR-Register-Stream thanks for this. This clarity was requested because the Banking Product Comparator requires the addition of `/cds-au/v1` to function:
![image](https://user-images.githubusercontent.com/4291448/94637185-449b6600-031a-11eb-9046-0339c2c2d565.png)

**Comment by CDR-Register-Stream** [comment]
@perlboy Noted that the product comparator is storing the base uri plus the prefix.

**Comment by CDR-Register-Stream** [comment]
Closing as this issue is covered in the [CDS Products Comparator repository](https://github.com/ConsumerDataStandardsAustralia/banking-products-comparator/issues/60)
