### ISSUE TITLE
Moving authentication with the CDR Register to the Software Product entity

### ISSUE THREAD

**Issue by CDR-Register-Stream** [cdr-register/register#144]
As part of introducing intermediaries into the Consumer Data Right, we have identified a design constraint with the authentication model of the CDR Register.

Currently, through the client authentication mechanism, ADRs are using the **Data Recipient Brand ID** as the client id for the client assertion.
 
### Current Non-normative example:
 
**Request CDR Register Access Token**
```
POST /token HTTP/1.1
Host: cdr.register
Content-Type: application/x-www-form-urlencoded
 
grant_type=client_credentials&
  client_id=<data recipient brand id>&
  client_assertion_type=urn%3Aietf%3Aparams%3Aoauth%3Aclient-assertion-type%3Ajwt-bearer&
  client_assertion=eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjEyNDU2In0.ey ...&
  scope=cdr-register%3Abank%3Aread

 
## Decoded client assertion JWT
{
  "alg": "PS256",
  "typ": "JWT",
  "kid": "b50641343f8f4717a4865d238b6297b8"
}
{
  "iss": "<data recipient brand id>",
  "sub": "<data recipient brand id>",
  "exp": 1516239322,
  "aud": "https://cdr.register/idp/connect/token",
  "jti": "37747cd1-c105-4569-9f75-4adf28b73e31"
}
 
```
 
We would like to move to a model where authentication would occur at the software product level, so one could potentially have different JWKS URIs for different software products if the deployments are handled by different parties. This will also extend to certificate management occurring at the software product level.

To achieve this, the  **Software Product ID** will be used as the client id for the client assertion
 
 
### Future Non-normative example:
**Request CDR Register Access Token**

```
POST /token HTTP/1.1
Host: cdr.register
Content-Type: application/x-www-form-urlencoded
 
grant_type=client_credentials&
  client_id=<software product id>&
  client_assertion_type=urn%3Aietf%3Aparams%3Aoauth%3Aclient-assertion-type%3Ajwt-bearer&
  client_assertion=eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjEyNDU2In0.ey ...&
  scope=cdr-register%3Abank%3Aread
 
## Decoded client assertion JWT
{
  "alg": "PS256",
  "typ": "JWT",
  "kid": "b50641343f8f4717a4865d238b6297b8"
}
{
  "iss": "<software product id>",
  "sub": "<software product id>",
  "exp": 1516239322,
  "aud": "https://cdr.register/idp/connect/token",
  "jti": "37747cd1-c105-4569-9f75-4adf28b73e31"
}

```
 
 
Impact is limited to the retrieval of access token to call the secure APIs on the CDR Register, i.e. [GetSoftwareStatementAssertion ](https://cdr-register.github.io/register/#getsoftwarestatementassertion-ssa)and [GetDataHolderBrands](https://cdr-register.github.io/register/#getdataholderbrands).
 
 
 
To achieve this, we are looking at a flexible change management approach to allow ADRs to coordinate their changes. Current thinking is we allow client authentication to occur at the CDR Register at both the ADR Brand and Software Product level, then deprecating ADR Brand authentication at a future date.

Certificate issuance at the Software Product level is not seen as an issue as there is currently only one software product per brand with the current participants, therefore migration will be straight forward.

Impact will be limited to current and incoming Data Recipients in the CDR Ecosystem. Data Holders do not currently call authenticated endpoints on the CDR Register and therefore are not impacted by this issue.

**Comment by WestpacOpenBanking** [comment]
Westpac is supportive of this change.

**Comment by WestpacOpenBanking** [comment]
Westpac does not foresee this change impacting our implementation and agrees with the proposed documentation changes.

**Comment by CDR-Register-Stream** [comment]
Closing as issue now documented in V1.3.0 of the CDR Register design
