### ISSUE TITLE
Constraints for ADRs updating registrations after their November 2020 compliance date

### ISSUE THREAD

**Issue by CDR-Register-Stream** [cdr-register/register#145]
November 2020 introduces the [CDR Arrangement Revocation](https://consumerdatastandardsaustralia.github.io/standards/#end-points) endpoint to be hosted by ADRs.
This endpoint location is propagated to DHs through updates to the ADR registration using V2 of the [SSA](https://cdr-register.github.io/register/#dynamic-client-registration). This SSA definition includes the `recipient_base_uri` field which replaces the `revocation_uri`.

It has been highlighted the `recipient_base_uri`, currently a **required** field, should technically be **optional** given ADRs as the `revocation_uri` isn't deprecated until Feb 2021. 

The `recipient_base_uri` field remaining **required** has the following impact:
**ADRs will not be able to update their registrations on a Data Holder if:**
1. They have have not exposed the `recipient_base_uri` field by 1st November 2020
2. AND they need to update an SSA field other than the `recipient_base_uri` post 1st November 2020

Attempts to make these changes would result in an error being returned when trying to update a registration with a Data Holder Brand.

Our position has evolved on this matter and we come to a default position where it **IS NOT** feasible to change the specification of the SSA definition given the impact to ADRs is extremely limited and the current timing in the release cycle. The `recipient_base_uri` will remain a **required** field.

I'd like to invite input into this thinking as no change will be considered unless a justification is provided to warrant an urgent change

**Comment by NationalAustraliaBank** [comment]
NAB believes that making the recipient_base_uri mandatory impedes the transition flexibility for ADR’s and  is not in line CDS v1.5.1 which implies that the recipient_base_uri will not be present in the SSA until the ADR supports the Arrangement Revocation endpoint.  Excerpt from CDS below.

In the interests of supporting a flexible transition across DH’s and ADR’s in line with CDS v1.5.1, NAB believes that recipient_base_uri should be optional ie. SSA either provides:
•	revocation_uri only
OR
•	Both revocation_uri and recipient_base_uri 
That way, the ADR has the flexibility to make updates to the SSA prior to making their Arrangement endpoint available.

**Data Holders calling Data Recipients**
Data Holders may discover that a given Data Recipient supports the CDR Arrangement Revocation End Point by the presence of the Recipient Base URI in the Software Statement Assertion (SSA). If a Data Recipient does not support the CDR Arrangement Revocation End Point, the Data Holder MUST call the Data Recipient Token Revocation End Point.
Data Recipients SHOULD update their client registration with each Data Holder as soon as is practical once they support the CDR Arrangement Revocation End Point.
Data Recipients MUST continue to support their Token Revocation End Point until February 2021 and until they have updated their client registrations.

**Comment by spikejump** [comment]
+1 @NationalAustraliaBank comment above.

The standard as defined today supports a flexible transition for both DH and ADR to CDS v1.5.1.  That flexibility is lost when `recipient_base_uri` is required in the SSA.  It means ADR must support CARE endpoint on Nov 1 2020 or before the ADR is required to update the SSA with the DHs.

**Comment by WestpacOpenBanking** [comment]
Westpac agrees with the ACCC’s position that it is not feasible to change the specification of the SSA definition given the limited impact to ADRs. In particular, we would not be able to accommodate changing ``recipient_base_uri`` to optional in November timeframes

**Comment by CDR-Register-Stream** [comment]
The decision was made not to change the specification for the SSA. Lessons learnt from this piece of work are to be captures in #161
