### ISSUE TITLE
Seeking clarification on Type and UType of Payee

### ISSUE THREAD

**Issue by SongqingGu** [cdr-register/register#146]
Our team is seeking clarification on Payee type and UType in PayeeDatail response. The response schema specifies three possible values, Domestic, Biller and International, which are mutually exclusive.  But sample response message gives us a different view.
{
  "payeeId": "string",
  "nickname": "string",
  "description": "string",
  "type": "BILLER",
  "creationDate": "string",
  "payeeUType": "domestic",
  "domestic": {
    "payeeAccountUType": "account",
    "account": {
      "accountName": "string",
      "bsb": "string",
      "accountNumber": "string"
    },
    .....
  },
  "biller": {
    "billerCode": "string",
    "crn": "string",
    "billerName": "string"
  },
  "international": {
    "beneficiaryDetails": {
      "name": "string",
      "country": "string",
      "message": "string"
    },
    ....
  }
}

There are 2 questions: 
1. what is the rationale to have pay type and UType at the same time?  it looks both of them tell the same thing.
2. the sample response message as shown above, shows type of "Biller" and payUType of "domestic", followed by all three options. The combination is right? or it should be one type, one payUType and one corresponding detailed one?

**Comment by CDR-Register-Stream** [comment]
@SongqingGu Thanks for your query.

This repository is dedicated to the CDR Register design and not on the Banking APIs. 

You would be best placed to re-submit your question to the Consumer Data Standards [maintenance repository](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues).

**Comment by CDR-Register-Stream** [comment]
Closing as question answered
