### ISSUE TITLE
Grant Type jwt-bearer incorrectly defined in the Registration Request 

### ISSUE THREAD

**Issue by CDR-Register-Stream** [cdr-register/register#147]
There is a defect in the [Registration Request](https://cdr-register.github.io/register/#registration-request-using-jwt) documentation.

As defined in [RFC 7523 section 2.1](https://tools.ietf.org/html/rfc7523#section-2.1), the jwt-bearer grant type is defined as: **"urn:ietf:params:oauth:grant-type:jwt-bearer"**

Within the [Registration Request](https://cdr-register.github.io/register/#registration-request-using-jwt) section of the CDR Register documentation, this grant type is incorrectly defined as: **urn:ietf:params:oauth:grant-type:jwtbearer** (not the missing dash in jwt-bearer). 
Note that the non-normative example provided is incorrect.

This issue has been raised to help identify what validation is currently in play for registration requests by data holders, to what degree this change needs to be managed within the ecosystem and to track the correction

**Comment by anzbankau** [comment]
We don't see this proposed change as impacting our implementation, and agree it is a good change to make to the documentation.

**Comment by WestpacOpenBanking** [comment]
Westpac does not foresee this change impacting our implementation and agrees with the proposed documentation changes.

**Comment by CDR-Register-Stream** [comment]
Error in the grant_type definition is now redundant as this grant_type has now been removed from the list of valid grant types.
Please refer to #54 for reference.

Closing
