### ISSUE TITLE
MTLS vs. Non MTLS URLs not Documented

### ISSUE THREAD

**Issue by perlboy** [cdr-register/register#148]
It is understood that the Production Register has separate Base URLs depending on whether the endpoint is protected by MTLS or not? This is not documented in the online documentation as being the case and, indeed, Biza's Heimdall simulation has been built to this online documentation.

Could the ACCC please document what base urls are applicable to what endpoints rather than the rather unhelpful information supplied as follows:
![image](https://user-images.githubusercontent.com/4291448/95418374-b575fa00-097a-11eb-88c8-65ce9e83bcda.png)

**Comment by CDR-Register-Stream** [comment]
@perlboy Thanks for your query.

This improvement to the documentation is a known issue and is currently being tracked under: #129

**Comment by CDR-Register-Stream** [comment]
Closing as a duplicate. Will track in issue #129
