### ISSUE TITLE
legalEntityId and dataRecipientId are the same

### ISSUE THREAD

**Issue by perlboy** [cdr-register/register#150]
In the 1.2.0 release the following line was added to the Identifiers table:
![image](https://user-images.githubusercontent.com/4291448/95524399-9deb4f80-0a14-11eb-9313-dc3b10e86b17.png)

This appears to imply that a single legal entity (ie. Company) **will only ever** have **one** Data Recipient registration within the Register?

How does the ACCC intend to solve for situations where multiple individual Data Recipient records may exist, for instance, in large enough organisations, with completely separate Data Recipient infrastructure under a single Legal Entity?

**Comment by CDR-Register-Stream** [comment]
@perlboy Thanks for your query. 

This is a good question and it would be beneficial to expand on this use case to understand how the current model applies and if there are any gaps.

The legal entity and data recipient concept is as you have described. There is only one record.
However, the model does incorporate brands. The original thinking is that brands can be used to segment across actual company brands as well as divisions of an organisation which as you say, may have separate infrastructure.

The endpoints are mapped against the brand so at a technical level, this flexibility exists. 

I'd be keen to understand how this model may, or may not apply to your use case.

**Comment by CDR-Register-Stream** [comment]
As discussed out of band, there is benefit in improving the entity model documentation outlined in the [Ecosystem Entities](https://cdr-register.github.io/register/#ecosystem-entities) section.

There is benefit in improving the documentation, mapping the entity model against differing use cases.

**Comment by perlboy** [comment]
Closing see https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/354

**Comment by CDR-Register-Stream** [comment]
Re-opening as this issue is being used to track the associated documentation improvement

**Comment by CDR-Register-Stream** [comment]
The CDR Support Portal article [Brands in the Consumer Data Right Ecosystem](https://cdr-support.zendesk.com/hc/en-us/articles/900005881263-Brands-in-the-Consumer-Data-Right-Ecosystem) has been published to document these differing use cases.

**Comment by CDR-Register-Stream** [comment]
Closing as the [Brands in the Consumer Data Right Ecosystem](https://cdr-support.zendesk.com/hc/en-us/articles/900005881263-Brands-in-the-Consumer-Data-Right-Ecosystem) covers this issue
