### ISSUE TITLE
Seeking clarification on client_id parameter in request for token

### ISSUE THREAD

**Issue by hfszeto2020** [cdr-register/register#151]
Hi,

Our team seeks clarification regarding where the `client_id` is derived from as the parameter for the Request for the CDR Register Token in https://cdr-register.github.io/register/#register-endpoints

```
POST /token HTTP/1.1
Host: cdr.register
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&
  client_id=12345&
  client_assertion_type=urn%3Aietf%3Aparams%3Aoauth%3Aclient-assertion-type%3Ajwt-bearer&
  client_assertion=eyJhbGciOiJQUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjEyNDU2In0.ey ...&
  scope=cdr-register%3Abank%3Aread
```

And just wondering if this is in anyway related to the dataRecipientBrandId mentioned here: https://cdr-register.github.io/register/#ecosystem-entities ?

![image](https://user-images.githubusercontent.com/72112558/95545715-34843480-0a46-11eb-82dc-1c732f5629da.png)

So according to this:

![image](https://user-images.githubusercontent.com/72112558/95545121-875cec80-0a44-11eb-998f-5d99bc97a58e.png)
it mentions that if the calling client is a Data Recipient Brand then it is the _Data Recipient Brand ID as issued by the CDR Register_. But where is this Recipient Brand ID derived? Based on our understanding as far as we are aware at that point there are no prior calls that can be made to the CDR Register (other than the call to the ODIC Config endpoint) and hence not quite clear on how the Recipient Brand would have been acquired in the first place?

**Comment by CDR-Register-Stream** [comment]
@hfszeto2020 Thank you for your query. 

Identifier for all entities, whether the legal entity, brand or software product, are only issued once they have been created on the Register. Therefore, you will only get access to these values through the onboarding process.

Its also worth noting that the public APIs which exposes this information to other participants, will only include your records once they have become active on the Register, which will occur after onboarding has been completed.

Please let me know if you require further clarification.

**Comment by CDR-Register-Stream** [comment]
Closing this issue as answered. If there are further questions, please feel free to raise a new issue
