### ISSUE TITLE
Request for Feedback: JWKS Key Management

### ISSUE THREAD

**Issue by CDR-Register-Stream** [cdr-register/register#153]
There is ambiguity about JWKS key rotation and associated cache management timing as the documentation doesn't explicitly call out how this use case should be managed.
 
The current assumption is that JWKS_URI clients will use the following caching approach:
1. Lookup key in JWKS_URI cache
2. IF key does not exist in cache OR cache has expired THEN refresh cache
3. IF key exists in cache, return key
4. ELSE return key not found

This approach is simple, but the cache expiration time is important.

Key rotation is expected for the following scenarios:
1. JWKS_URI owner rotates key on a regular basis as a security hygiene task
2. JWKS_URI owner rotates key due to compromised key

Scenario 1 is catered for when the key is not found in the the JWKS_URI cache. A refresh simply brings the new key into the cached set. 
However, Scenario 2 highlights that a compromised key is only removed from the set when all clients refresh their cache.

Therefore, cache refresh times should be set to a value that ensures caching is still useful while minimising the time that a compromised key can remain active within the ecosystem.

Lifetime of security assets and information varies throughout the [CDR Register design](https://cdr-register.github.io/register/#introduction) and [CDS ](https://consumerdatastandardsaustralia.github.io/standards/#introduction) but short lifetime assets fit in the window of 2-10 mins. For the sake of simplicity, our initial proposal is we would recommend a **5 min** cache time.

We invite feedback from the community on what they consider best practice to satisfy these scenarios and how a **5 minute** cache time may affect their implementations.

**Comment by NationalAustraliaBank** [comment]
NAB supports the inclusion of the outlined cache management approach for JWKS keys within the CDR standards. We recommend a range of 5-15 minutes which will enable the participants to select a cache timeout to appropriately balance the load and the risk.

**Comment by perlboy** [comment]
I'm not sure it's critical that a specific cache management approach be mandated by the ACCC. It seems like this is a decision for Holders to make around their security posture. What I would suggest is an upper bound as caching can impact key rotation abilities.

**Comment by anzbankau** [comment]
ANZ supports guidelines being specified to help participants understand the maximum they could cache this data for. We agree that somewhere in the 5-15 minutes range would be appropriate.

**Comment by CDR-Register-Stream** [comment]
ACCC's current position is to define an upper bound of 10 minutes. This aligns to the access token lifetime. 

Further security review is occurring and will be updated on this thread once this decision is complete

**Comment by CDR-Register-Stream** [comment]
ACCC's security review on this topic is complete. We now have the following position:

_ACCC recommends that the upper bound is constrained to 15 minutes with an additional recommendation that timeout period be configurable (not hard coded) to cater for the case where the timeout needs to change due to a threat or breach._


Feedback for this issue will remain open until 15/03/21

**Comment by CDR-Register-Stream** [comment]
This recommendation has been documented in the [JWKS Cache Management section](https://cdr-register.github.io/register/#jwks-cache-management) in V1.4.0 of the CDR Register design
