### ISSUE TITLE
Term Deposit - clairification on Lodgement Date

### ISSUE THREAD

**Issue by LizLau** [cdr-register/register#155]
Hello,
Can we please clarify the definition of lodgementDate on the schema in the standards document for BankTermDepositAccount.
Definition is Lodgement Date of the Original Deposit.

At AMP:-
1) When a TD is first created, we have a start date (date of when the TD starts accumulating interest).
2) When a TD is renewed and it's the same term as the original TD (the original TD continues and the original start date remains unchanged)
3) When a TD is renewed and the terms are different, we terminate the original TD and create a new one. In this scenario, there is no relationship kept between the original TD and the new one. We will need to use the new start date

We wanted to confirm the definition of lodgement date:-
1) Is it the original start date OR
2) Date of renewal

If option 1 is correct, then are you ok for us to use the original start for renewals on the same term, and the new start date for new term deposits and renewals with different terms.

Kind regards
Liz

**Comment by CDR-Register-Stream** [comment]
@LizLau Thanks for your query.

Your question regarding term deposits relates to the Consumer Data Standards, maintained in their [standards-maintenance repository](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance).

Please raise your query there. The register repository is intended for CDR Register design collaboration only.

**Comment by CDR-Register-Stream** [comment]
closing issue as answered. Please create a new issue if you have further questions
