### ISSUE TITLE
Documentation Improvement: Entity model should reflect GetMetrics collection per Brand

### ISSUE THREAD

**Issue by CDR-Register-Stream** [cdr-register/register#158]
Currently the entity model doesn't outline that metrics as per the [GetMetrics API](https://consumerdatastandardsaustralia.github.io/standards/#get-metrics), are collected on a per brand basis.

The entity model needs to be updated to reflect this.

**Comment by nils-work** [comment]
Hi @CDR-Register-Stream 
Is this related to [this withdrawn change request](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/307)?
I think previous guidance from the DSB was that Metrics are at the Data Holder level. Is this changing?

**Comment by nils-work** [comment]
May also be related to #124

**Comment by WestpacOpenBanking** [comment]
Currently, we are providing one Get Metrics API across our brands. The DSB has previously clarified in response to a Zendesk question raised by us that “There is nothing in the CDR standards to prohibit this”. Is the intention of this update to require one Get Metrics API per brand or to simply clarify from an entity model perspective the relevant URI applies at brand level? We note that the number of brands may be very large in the case of white labelling of products, for example.

**Comment by CDR-Register-Stream** [comment]
@WestpacOpenBanking and @nils-work. Thanks for your input. 

The CDR Register collects metrics per data holder brand. The [Brands in the Consumer Data Right](https://cdr-support.zendesk.com/hc/en-us/articles/900005881263-Brands-in-the-Consumer-Data-Right-Ecosystem) article helps articulate how brands are conveyed and how the Register collects this information.

**Comment by CDR-Register-Stream** [comment]
The CDR Register design ecosystem entities section has been updated to clarify that metrics are collected per data holder brand

**Comment by CDR-Register-Stream** [comment]
Closing as complete
