### ISSUE TITLE
Correct PPID typo in Sector Identifiers section

### ISSUE THREAD

**Issue by nils-work** [cdr-register/register#176]
The first sentence of **Sector Identifiers** uses the incorrect name for PPID.

Please update to use the [correct](https://openid.net/specs/openid-connect-core-1_0.html#Terminology) [name](https://consumerdatastandardsaustralia.github.io/standards/#security-profile) -
> As per the Consumer Data Standards, the ~~Pairwise Pseudonym Identifier (PPD)~~ **Pairwise Pseudonymous Identifier (PPID)**

**Comment by CDR-Register-Stream** [comment]
@nils-work Thanks for highlighting this issue. I have attached it to [Design Maintenance Iteration 2](https://github.com/cdr-register/register/projects/11) to address.

**Comment by CDR-Register-Stream** [comment]
Change included in V1.5.0


Closing as complete
