### ISSUE TITLE
The kid and x5t values need swapped. See https://datatracker.ietf.org/doc/html/rfc7517

### ISSUE THREAD

**Issue by steveoshima** [cdr-register/register#184]
Describe the bug
Noticed a major bug in around the JWKS generation. The kid and x5t values need to be swapped.
SSA JWTs have the same issue.

To Reproduce

See jwks response i.e. https://api.cdr.gov.au/idp/.well-known/openid-configuration/jwks
See ssa endpoint responses i.e. /cdr-register/v1/banking/data-recipients/brands/<brand>/software-products/<softwareid>/ssa

Expected behaviour
kid values and x5t values to follow standards defined in
https://datatracker.ietf.org/doc/html/rfc7517
https://datatracker.ietf.org/doc/html/rfc7638

x5t is a base64url-encoded SHA-1 thumbprint (a.k.a. digest) of the DER encoding of an X.509 certificate.

Additional context
Example of values that need to be swapped
"kid": "AA24F185EE3F67504808FC4E26B135B99E63BDA9",
"x5t": "qiTxhe4_Z1BICPxOJrE1uZ5jvak",

kid is defined by using values "e", "kty", "n" from the JWK, maintain lexicographic order of "e","kty","n" then based64url-encode this using SHA-1. Please see https://datatracker.ietf.org/doc/html/rfc7638#section-3.1.
Recommend you use the same sha size as the live CDR register. Is this sha1 or sha256?

The x5t values you have are actually kid values and the kid values you have are actually the x5t values.
Please swap them around.

**Comment by steveoshima** [comment]
Further x5t info:

The x5t value being wrong can be simply proven by using command:
openssl x509 -noout -fingerprint -sha1 -inform pem -in  [certfile.crt]
e.b. outputs Fingerprint=54:2A:9B:91:60:04:88:08:8C:D4:D8:16:91:6A:9F:44:88:DD:26:51
This thumprint value minus the colons is what a x5t should be.

**Comment by steveoshima** [comment]
Further kid info:

The kid stands for key id. The key is a private or public key, not a reference to the full x509 certificate.

Please see RFC https://datatracker.ietf.org/doc/html/rfc7638#section-5 it clearer states:
_while logically equivalent to a digest of the SPKI representation of the key, a JWK Thumbprint is computed over a JSON representation of that key, rather than over an ASN.1 representation of it._
Concerning what is a kid is vs an x5t

https://datatracker.ietf.org/doc/html/rfc7638#section-3.4
_A typical usage is for the producer of the key to use the base64url-encoded JWK Thumbprint value as a "kid" (key ID) value.  In this case, the consumer of the "kid" treats it as an opaque value that it uses to select the key._

**Comment by steveoshima** [comment]
Raised ticket with production CDR register.
https://github.com/cdr-register/register/issues/184

**Comment by steveoshima** [comment]
In not following the standards it will mean "data holder" and "data recipients" devs will have to work around this, adding code and certificate lookups in places that should not be required.

i.e. creating the id_token requires a private key for signing. The private key is converted to JWK and from that the kid placed in the id_token JWT header. If we now have to use an x5t as the kid value (breaking the RFC standards) then we need to also fetch the public DER cert and use other libraries to build the thumbprint.

**Comment by michael-wilson-au** [comment]
This is not the correct JWKS endpoint for validating the SSA https://api.cdr.gov.au/idp/.well-known/openid-configuration/jwks
You should be using https://api.cdr.gov.au/cdr-register/v1/jwks as describer in the CDR Register Design Reference https://cdr-register.github.io/register/#getjwks

**Comment by steveoshima** [comment]
Thanks 
I was not using https://api.cdr.gov.au/idp/.well-known/openid-configuration/jwks as a place to validate ssa but an example.

If jJWKS and SSA kid values are generated to this standard then I see no problem.
https://api.cdr.gov.au/cdr-register/v1/jwks looks to be correct.

**Comment by steveoshima** [comment]
Q. regarding 
https://api.cdr.gov.au/idp/.well-known/openid-configuration/jwks
vs
https://api.cdr.gov.au/cdr-register/v1/jwks

Why there two different methods to calculate the kid value?

**Comment by CDR-Register-Stream** [comment]
@steveoshima thanks for your query.

As @michael-wilson-au commented, https://api.cdr.gov.au/cdr-register/v1/jwks is used for signature validation on the SSAs generated by the CDR Register.

This is the key use case which is published in the [Registration Flows](https://cdr-register.github.io/register/#registration-flows) section of the CDR Register Design.


Other JWKS endpoints are not utilised against use cases specifically documented in the CDR Register Design.


Please let me know if you require further clarification.

**Comment by CDR-Register-Stream** [comment]
Closing as complete with response provided.
