### ISSUE TITLE
Rules of engagement

### ISSUE THREAD

**Issue by opendatahub** [cdr-register/register#2]
Hi ACCC,

Could you explain what the rules of engagement are for raising issues are? Do you intend to follow the model of https://github.com/ConsumerDataStandardsAustralia/standards and raise issues yourselves as topics for comment and/or should issues be directly raised by anyone (like this one), or both?

**Comment by CDR-Register-Stream** [comment]
Rules of engagement are outlined at: [https://github.com/cdr-register/register](https://github.com/cdr-register/register) and are derived from the Consumer Data Standards Australia.

Dedicated issues have been created and feel free to add your comments. As more content is rolled out, associated dedicated issues will be created
