### ISSUE TITLE
Consent Revocation - Communication between Data Holder and ADR

### ISSUE THREAD

**Issue by bmangalaganesh** [cdr-register/register#20]
The specs expect an ADR to notify the Data Holder if a consent is withdrawn.

_(Source Page: 33 of Exposure Draft Document)_
> If a consent to collect particular CDR data is withdrawn in accordance with this
> rule, the accredited person must, in accordance with the data standards, notify the
> data holder of the withdrawal. 

There is no standard API defined (or an alternative mechanism defined) by the Data Holder which can be invoked by an ADR to notify them of the withdrawal. Similarly, the ADRs do not expose any API for a Data Holder to use for notification.

_(Source Page:39 of Exposure Draft Document)_
> If an authorisation is withdrawn in accordance with this rule, the data holder must, in accordance with the data standards, notify the accredited person of the withdrawal.

How are the  ADRs and Data Holders expected to  meet this requirement?

Appreciate any help/assistance.

**Comment by CDR-Register-Stream** [comment]
Thanks for your question.

An [ecosystem component diagram](https://cdr-register.github.io/register/#ecosystem-component-diagram) is provided to detail that ADRs are required to expose endpoints both to facilitate client authentication and consent withdrawal notifications from Data Holders..

The [CDS ](https://consumerdatastandardsaustralia.github.io/standards/#end-points) specifies how the Data Holder calls the Data Recipient revocation endpoint.

**Comment by CDR-Register-Stream** [comment]
Closing as response has provided. If there are future questions, please feel free to raise a new issue in this repository
