### ISSUE TITLE
Usage of CDR register during an API call from ADR to a Data Holder

### ISSUE THREAD

**Issue by bmangalaganesh** [cdr-register/register#21]
Whenever an API call comes from an ADR to a Data Holder, the Data Holder will first validate that status of the ADR (and its software product) is active prior to servicing the request.

Does the specs expect this validation to be performed via a call to the CDR register (which is a huge overhead) or using the cache copy that is maintained by the Data Holders?

The Cache copy may be outdated by up to _5 minutes_ based on the specs

**Metadata Cache Management Metrics**
Maximum Time between Cache Refresh Metadata Request  and call to Discovery API  5 mins

There is a window of risk (upto 5 mins) when a suspended, revoked, reactivated or surrendered ADR might access the CDR data (if we rely on the Cache)

What is the mitigation plan or approach that the Data Holders are expected to adopt for this scenario?

**Comment by CDR-Register-Stream** [comment]
Metadata caching requirements are documented [here](https://cdr-register.github.io/register/#metadata-cache-management)

It is expected that Data Holders will cache the status of both ADRs and Software products within the Regime and will be able to respond to status changes within a 5 minute period.

Yes a window of risk exists and 5 minutes has been deemed an acceptable amount of time to allow DHs to react to change.

**Comment by CDR-Register-Stream** [comment]
Closing. If further discussion is required, please raise a new issue and feel free to reference this one
