### ISSUE TITLE
Notification Requirements - ADR and Data Holder

### ISSUE THREAD

**Issue by bmangalaganesh** [cdr-register/register#27]
Have a query regarding Notification requirements particularly in the context of notifications that must be provided outside the consumer dashboard.

Couple of examples from the spec is shown below to provide the context

> A CDR receipt must be given in writing otherwise than through the CDR consumer’s consumer dashboard.  (Pg 46)

> The notification must be given in writing otherwise than through the CDR consumer’s consumer dashboard. (Pg 47)

What are considered as valid channels for these notifications? email, postal mail (sounds archaic but is a valid channel/medium) and possibly SMS sounds logical.

Is a "secure email" considered a valid channel for these purposes?

**Comment by CDR-Register-Stream** [comment]
@bmangalaganesh Thank you for your query

It is open to accredited persons to determine how they meet these requirements and the ACCC does not intend to specify (outside of the consumer dashboard) how the notification requirements or CDR receipts should be provided. The ACCC considers the examples provided; email, secure email, post and SMS to all be valid channels for providing CDR receipts and notifications.

For completeness, we also note rule 4.13(1)(a) requires consumers to be able to withdraw their consent in writing too. We have previously provided feedback to stakeholders that requiring a consumer to verify themselves before they are able to withdraw consent is acceptable. This could be through a login or authentication step on a website, for example. Where an accredited person requires a consumer to verify themselves before withdrawing consent, the two business day requirement in rule 4.13(2)(a) takes effect from the day the accredited person has verified the identity of the consumer. 

Please let us know if you have any further questions.

**Comment by CDR-Register-Stream** [comment]
Closing. If further discussion is required, please raise a new issue and feel free to reference this one
