### ISSUE TITLE
Metadata Cache component at the data holder

### ISSUE THREAD

**Issue by bmangalaganesh** [cdr-register/register#28]
In the [Ecosystem Component Diagram section](https://cdr-register.github.io/register/#ecosystem-component-diagram), in the data holder section, the docs state that metadata Cache as follows:

> Cache of discovered Data Holders within the CDR ecosystem. Caching rules and logic are described at: Cache Refresh Metadata Request

Shouldn't this be a cache of discovered ADRs instead of Data Holders?

Thanks

**Comment by kaveenr** [comment]
Seems like this was updated, https://cdr-register.github.io/register/#data-holder-2

**Comment by CDR-Register-Stream** [comment]
@bmangalaganesh Thanks for raising this issue with the documentation.

This section was updated to the following:

_Cache of discovered Accredited Data Recipients and their associated Software Products within the CDR ecosystem. Caching rules and logic are described at: Metadata Cache Management_
