### ISSUE TITLE
Integration Timelines

### ISSUE THREAD

**Issue by da-banking** [cdr-register/register#29]
DA is developing the Data Holder solution for a number of ADIs.

We're seeing the Registry take conceptual shape. As the Initial Data Holders will be going live in under 4 months, there must be some planning to support their integration and launch.

At some point the other Data Holders need to develop integration with an instance of the Registry, and later go through testing against a test instance.

We were wondering if you were in a position to outline how and when this integration and testing is expected to occur? 

Even in very broad terms, some indication would help us and our ADI clients align our schedules and resources.

Apologies if this is information is already available somewhere, we haven't been able to find it.

Thanks!

**Comment by CDR-Register-Stream** [comment]
The ACCC is working towards providing further information about onboarding processes for participants who are not currently involved in Industry Testing. We will provide this information as soon as possible.

We recommend you “Sign up to the ACCC’s [consumer data right newsletter](https://www.accc.gov.au/media/subscriptions/consumer-data-right-updates) to receive updates on our consumer data right work for open banking and energy.” You can subscribe by using the link above or find it on the CDR page of the ACCCs website.
