### ISSUE TITLE
Feedback 30 - Dedicated Data Recipient API Metadata

### ISSUE THREAD

**Issue by CDR-Register-Stream** [cdr-register/register#30]
This thread has been created to allow for feedback on the use cases that a dedicated Data Recipient API would satisfy.

Currently the [GetSoftwareStatementAssertion](https://cdr-register.github.io/register/#getsoftwarestatementassertion-ssa) API satisfies the use case for dynamic registration and includes fields as defined in [SSA Definition](https://cdr-register.github.io/register/#dynamic-client-registration)

There are fields which can be used for additional scenarios, such as logos and organisational details. We would like to identify what additional information is required to satisfy these additional use cases such as dashboard display.

For contributions, please outline what use case you need to satisfy and the data recipient fields you anticipate.

All feedback is welcome.

**Comment by commbankoss** [comment]
As discussed during the weekly ACCC registry design phone call, Commonwealth Bank are supportive of a separate API resource to manage 'business' information about an ADR. Our recommendation would be to include, ADR name, software name, software description, URL logo, ADR status and Software status.

**Comment by CDR-Register-Stream** [comment]
Thanks for all the feedback. This is an old thread so I'll be closing it with references.

A [GetDataRecipients API ](https://cdr-register.github.io/register/#getdatarecipients)was defined to satisfy the usecases for retrieving the relationships between [ADR entities](https://cdr-register.github.io/register/#ecosystem-entities) (Legal Entity, Data Recipient Brand and Software Product) as well as providing the metadata to display the consumer dashboard
