### ISSUE TITLE
Delete a Client Registration  - Method not allowed scenario

### ISSUE THREAD

**Issue by bmangalaganesh** [cdr-register/register#35]
https://cdr-register.github.io/register/#delete-a-client-registration-for-a-given-client-id states the following response scenarios

Status | Meaning | Description | Schema
-- | -- | -- | --
204 | No Content | Client deleted | None
401 | Unauthorized | Request failed due to unknown or invalid Client or invalid access token | None
403 | Forbidden | The client does not have permission to read, update or delete the Client | None
405 | Method Not Allowed | The client does not have permission to read, update or delete the Client | None

What is the difference between 403 and 405?

Aren't the Data Holders expected to expose the DELETE /register/{ClientId} or is that optional at this stage?

**Comment by CDR-Register-Stream** [comment]
@bmangalaganesh Thankyou for raising this issue.
The description for status 405 is incorrect and needs to be updated.

[405 ](https://tools.ietf.org/html/rfc7231#section-6.5.5) is defined as: 

_The 405 (Method Not Allowed) status code indicates that the method
   received in the request-line is known by the origin server but not
   supported by the target resource_

Given that this is currently an [optional endpoint](https://cdr-register.github.io/register/#client-registration-management), I would expect this error code to be returned if it is unsupported.

This issue will be kept open to track the updates to the 405 description

**Comment by CDR-Register-Stream** [comment]
This has now been resolved and documented in release 1.1.1.

Closing as complete
