### ISSUE TITLE
ID token encryption

### ISSUE THREAD

**Issue by WestpacOpenBanking** [cdr-register/register#38]
Currently, the technical standards [mandate](https://consumerdatastandardsaustralia.github.io/standards/#tokens) ID token encryption, and the Open ID Connect Core normative reference [states](https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.3.1.3.7) that details of the keys and algorithms used to the encrypt the algorithms are to be exchanged through client registration. The registry specification does not include these details in the dynamic client registration sections. There are two options to resolve the issue: 
 
1.	Remove ID token encryption and any PII claims from the data standards.
2.	Add these details to the dynamic client registration specification. 
 
We believe that Option 1 is the most pragmatic approach in support of February implementation.
 
We have also [raised](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/45#issuecomment-562408716) an issue in the standards-maintenance repository.

**Comment by commbankoss** [comment]
Commonwealth Bank support's the above post made by @WestpacOpenBanking.

We also recommend removing first name and last name from ID token payload and defer encryption until later phases when appropriate use case is identified.

Apart from simplification for both ADRs and ADHs, encryption removal will require no additional changes for IDPs (specific encryption support and discovery) and dynamic client registration (on-boarding and SSA updates).

**Comment by pcurtisrab** [comment]
Regional Australia Bank offers a 3rd alternative approach as follows:

The standards should elevate preferred key management alogrithms (presumably, `RSA-OAEP` and `ECDH-ES`) to _Required_ in the [JWA 4.1 Implementation requirements](https://tools.ietf.org/html/draft-ietf-jose-json-web-algorithms-40#section-4.1), and mandate that Data Holders and Data Recipients as a minimum ONLY implement support for those [key management](https://tools.ietf.org/html/draft-ietf-jose-json-web-algorithms-40#section-4.1) and [content encryption](https://tools.ietf.org/html/draft-ietf-jose-json-web-algorithms-40#section-4.1) algorithms which are Required by JWA.

This reduces implementation burden on Data Holders and Data Recipients and mitigates compatibility issues. Our [full rational is here](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/58).

**Comment by perlboy** [comment]
> The standards should elevate preferred key management alogrithms (presumably, `RSA-OAEP` and `ECDH-ES`) to _Required_ in the [JWA 4.1 Implementation requirements]

@pcurtisrab I believe this relates to #36, I suspect first implementations will only ever use RSA. Aligning to similar structures in discovery documents, even if there is only one value, seems like a good starting point, from there adding new algorithms can be part of lifecycle cadence.

**Comment by omahoco** [comment]
86400 concurs with Wespac and CBA proposal to defer ID token encryption, until such point as it is required.

**Comment by perlboy** [comment]
While I support the sentiment above and this aligns with OBIE at the moment (ie. signed only tokens) is this the right place for this discussion? This is a specific change to the CDS, the Register component appears to be more discovery driven. Should (or maybe is? if so could it be reference a duplicate issue be raised within `standards-maintenance`? The existing link provided by @pcurtisrab seems to relate to discovery only?

**Comment by acccivan** [comment]
Impact to Register design is covered by issue #40

Discussion on support for encryption is covered in the Consumer Data Standards [standards-maintenance repository ](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/58)

**Comment by CDR-Register-Stream** [comment]
Released in 1.1.0. Closed as completed
