### ISSUE TITLE
Feedback 39 - Pairwise identifier algorithm sector_identifier_uri support 

### ISSUE THREAD

**Issue by CDR-Register-Stream** [cdr-register/register#39]
As defined by the [CDS](https://consumerdatastandardsaustralia.github.io/standards/#identifiers-and-subject-types), the identifier for an authenticated end-user (subject) MUST be passed in the `sub` claim of an [ID Token](https://openid.net/specs/openid-cocnnect-core-1_0.html#IDToken) and [UserInfo](https://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse) response as defined by [OIDC]

The Data Holder MUST generate the `sub` value as a Pairwise Pseudonymous Identifier (PPID) as described in [section 8](https://openid.net/specs/openid-connect-core-1_0.html#SubjectIDTypes) of [OIDC]. Furthermore, the identifier MUST be unique per customer as per the definition of customer in the CDR Federation section of this profile.

As per the OIDC standards, the identifier is generated using a sector identifier and a local account id.

The options for the sector identifier are as follows
	**1.** the common hostname for all **redirect_uris** as defined during the registration process
	**2.** the hostname of the **sector_identifier_uri**

**redirect_uris:**
All the hostnames defined in the **redirect_uris** array must be the same. If not, then **sector_identifier_uri** must be used

**sector_identifier_uri:**  
When a sector_identifier_uri is provided, the host component of that URL is used as the Sector Identifier for the pairwise identifier calculation. The value of the **sector_identifier_uri** MUST be a URL using the https scheme that points to a JSON file containing an array of redirect_uri values. The values of the registered redirect_uris MUST be included in the elements of the array.

During the initial release of the CDR Regime, will ADRs need support for multiple hostnames (and therefore require **sector_identifier_uri** supported) or will **redirect_uris** be sufficient?

For **sector_identifier_uri** support, a new field would be required in the DCR SSA which would be optionally provided, indicating **sector_identifier_uri** hostname is to be used as the Sector Identifier

**Comment by mperryau** [comment]
Ping Identity recommends that **sector_identifier_uri** be the supported option for the initial release of the CDR. Our customers, who are well advanced in implementing their CDR-compliant systems, need to support multiple hostnames in this release.

**Comment by perlboy** [comment]
> For sector_identifier_uri support, a new field would be required in the DCR SSA which would be optionally provided, indicating sector_identifier_uri hostname is to be used as the sector_identifier

What is `sector_identifier`? This appears to be a mistype, I believe there is only `sector_identifier_uri` at play here.

Specifically on `sector_identifier_uri` the upstream standard clearly states clear guidance of support when pairwise subjects are in use:
>Providers that use pairwise sub (subject) values SHOULD utilize the sector_identifier_uri value provided in the Subject Identifier calculation for pairwise identifiers.

And clarifying the word should from RFC2119:
> 3. SHOULD   This word, or the adjective "RECOMMENDED", mean that there may exist valid reasons in particular circumstances to ignore a particular item, **but the full implications must be understood and carefully weighed before choosing a different course**.

If this is a serious evaluation of whether there is an intention to **not** follow a clear recommendation from the upstream standard please provide appropriate evaluation of the _full implications_.

**Comment by ttranatping** [comment]
[The OIDC specifications](https://openid.net/specs/openid-connect-core-1_0.html#PairwiseAlg) note: "Providers that use pairwise sub values and support Dynamic Client Registration [OpenID.Registration] SHOULD use the sector_identifier_uri parameter. It provides a way for a group of websites under common administrative control to have consistent pairwise sub values independent of the individual domain names. It also provides a way for Clients to change redirect_uri domains without having to reregister all of their users."

Not supporting the sector_identifier_uri claim would make it different for ADR's to adjust their domain name for the same client. If I understand it correctly, users would need to reregister their consent, etc.

Also, on a slightly separate topic, without the sector_identifier_uri there is a presumption that hostnames are part of the redirect uri. This makes it hard to determine how custom schemes (for native apps) would work without a sector_identifier_uri. I have been told that there has been previous consensus that only https schemes should be used, but I can't find that information anywhere in the CDS or Client Registration standards.

**Comment by CDR-Register-Stream** [comment]
@perlboy sector_identifier is an input to the [Pairwise Identifier Algorithm](https://openid.net/specs/openid-connect-core-1_0.html#PairwiseAlg)

The purpose of obtaining feedback on this issue is to obtain additional data points on the implications of supporting the sector_identifier_uri at initial release and post release milestones.

**Comment by perlboy** [comment]
> @perlboy sector_identifier is an input to the [Pairwise Identifier Algorithm](https://openid.net/specs/openid-connect-core-1_0.html#PairwiseAlg)

No, it isn't, `sector_identifier` exists as neither a claim nor attribute in the referenced content. Do you mean _Sector Identifier_?

> The purpose of obtaining feedback on this issue is to obtain additional data points on the implications of supporting the sector_identifier_uri at initial release and post release milestones.

If the requirement for CDR is to support multiple hostnames and therefore multiple `redirect_uri`'s the guidance in the spec is clear, the implementer should implement `sector_identifier_uri`.

**Comment by CDR-Register-Stream** [comment]
For reference, this issue was raised in response to feedback on the Register design and previous discussion has occurred as part of the CDS InfoSec stream:
https://github.com/ConsumerDataStandardsAustralia/infosec/issues/48

**Comment by CDR-Register-Stream** [comment]
The issue description has now been updated to refer to Sector Identifier as a proper noun to ensure consistency with the standards

**Comment by perlboy** [comment]
I hadn't seen that issue. Considering the evaluation at the time was "no spec defined" I would suggest, for reasons noted by the FAPI WG member, alignment with upstream standard seems appropriate.

**Comment by anzbankau** [comment]
ANZ broardly supports the concept of introducing the sector_identifier_uri but have concerns around timing of this change and how this will fit with the current test activity. 
We currently support option 1 (as per standards) and will not be able to comment on the change without understanding when this would be introduced in order to assess the impact on the current testing.

**Comment by pcurtisrab** [comment]
From a data recipient perspective, Regional Australia Bank prefers option 2.

We foresee the potential need to use various hostnames in multiple `redirect_uri` in our initial use cases. We don't know yet, but we may need the flexibility. It seems possible to workaround the restriction using HTTP redirects, but without the benefit of hindsight, it is difficult for us to understand the full implications doing so.

Separate to the point at issue, we consider that the agility in the `redirect_uri` hostnames afforded by employing the hostname of `sector_identifier_uri` is valuable in protecting the customer experience (as [mentioned](https://github.com/cdr-register/register/issues/39#issuecomment-563074345) by @ttranatping) as our infrastructure develops. Given the high CX impact of losing all consents, the `sector_identifier_uri` is attractive as a protective measure.

**Comment by WestpacOpenBanking** [comment]
We agree with the position put forward by [ANZ bank](https://github.com/cdr-register/register/issues/39#issuecomment-564765407) on this issue. That is, we support introducing sector_identifier_uri, but we are concerned around the timing of this change and the effects on current testing activity.

**Comment by omahoco** [comment]
86400 supports the concept of introducing the sector_identifier_uri, given the implications for ADR's that may wish to adjust their domain names in the future.

**Comment by commbankoss** [comment]
This is more of an ADR concern than a ADH issue. Longer term, Commonwealth Bank supports the introduction of the sector_identifier_uri as it will allow data recipients to use multiple hostnames for the redirect URIs.
Introducing this requirement for current implementation would require changes for the registry, data holders and data recipients. There is no immediate value in this change as none of the data recipients have a need to support multiple hostnames.
In Commonwealth Bank's view this section of the standard should remain as-is for go-live, and the proposed change be introduced later, when the need is clear.

**Comment by spikejump** [comment]
Intuit supports the introduction of sector_identifier_uri.  It allows the ADRs to change their domains without losing existing consents.

**Comment by NationalAustraliaBank** [comment]
NAB supports option 1.

We assume if multiple hosts are provided in the redirect_uri claim the registration will be rejected.

**Comment by CDR-Register-Stream** [comment]
Thank you all for your input.

The ACCC has decided that although sector_identifier_uri support in the regime is warranted, the [CDR Register design](https://cdr-register.github.io/register/#dynamic-client-registration) will not support this field in the initial release. 

We will target a future release for this support
