### ISSUE TITLE
Feedback 43 - Revisiting Data Holder Metadata Update

### ISSUE THREAD

**Issue by CDR-Register-Stream** [cdr-register/register#43]
The current Register design mandates that Data Holders expose the [Metadata Update endpoint]( https://consumerdatastandardsaustralia.github.io/standards/#metadata-update) to allow Data Recipient statuses (Legal Entity and Software Product) information to propagate to the Data Holders in near-real-time through the push notification mechanism driven by the Register.

Data Holders are already required to poll the [GetSoftwareProductStatus](https://cdr-register.github.io/register/#getsoftwareproductsstatus) and [GetDataRecipientStatus](https://cdr-register.github.io/register/#getdatarecipientsstatus) endpoints every 6 hours to keep their Metadata Cache up to date. 

The current thinking is that for initial release, increasing this poll frequency to between 2-5 mins (depending on the amount of time it takes the Data Holder to persist this status information in their infrastructure) will initially be sufficient to propagate Data Recipient status information (legal entity and software product) from the CDR Register through to the Data Holders in the ecosystem.

We are proposing to remove the requirement for Data Holders to host the Metadata Update endpoint for the initial release, but keeping this requirement in scope for a future release to improve the  scalability of the ecosystem. This MVP approach will reduce the initial build requirements for Data Holders and simplifies initial testing of recovery scenarios.

**Comment by commbankoss** [comment]
Commonwealth Bank supports the recommendation to remove meta data refresh from ADRs and Data Holders.

**Comment by anzbankau** [comment]
ANZ would support the removal of the metadata update endpoint on the basis that it is not reintroduced at a later date. ANZ has progressed delivery according to the current standard and it will not simplify our position removing and then reintroducing this requirement. If there is potential for the metadata end-point to be reintroduced in subsequent release, then ANZ’s view is to maintain the current standard for the initial release.

**Comment by pcurtisrab** [comment]
The request for clarification states:

> _Data Recipients_ are already required to poll the GetSoftwareProductStatus and GetDataRecipientStatus endpoints every 6 hours to keep their Metadata Cache up to date.

Is this meant to be _Data Holders_?

**Comment by perlboy** [comment]
While we are generally supportive of removing any endpoints which are not deemed necessary we believe a series sequence flow diagrams for a set of scenarios ACCC wishes to ensure technological suitability for would be helpful.

> If there is potential for the metadata end-point to be reintroduced in subsequent release, then ANZ’s view is to maintain the current standard for the initial release.

Requirements change and backlogs (of which there are many) are modified, this is the nature of building an ecosystem. In actual fact we are now discarding software already written but are supportive of this reevaluation on the basis of ecosystem success.

**Comment by CDR-Register-Stream** [comment]
@pcurtisrab Good catch on the issue. I have corrected the issue description to **Data Holders**

**Comment by WestpacOpenBanking** [comment]
Westpac’s position is similar to the position [expressed by ANZ bank](https://github.com/cdr-register/register/issues/43#issuecomment-564766041) on this matter. We have also worked to deliver against the current specifications. It does not simplify matters for us if this requirement is removed and then reintroduced. Hence, if there is potential to reintroduce this functionality in a subsequent release, we agree that it should be maintained in the standard for the initial release.
 
If this modification is made to the specifications, we are keen to understand the behaviour that should occur in various outage scenarios. For example, suppose that a data holder’s polling service experiences an outage. How long should data holders be able to rely on their own internal status cache before they stop sharing data?

**Comment by SachiniSiriwardene** [comment]
What's the status on this issue? Also, will there be a sandbox endpoint provided to test the status update for the metadata cache?

**Comment by NationalAustraliaBank** [comment]
NAB supports the recommendation to remove metadata refresh endpoint from Data Holders.

**Comment by CDR-Register-Stream** [comment]
Thank you all for your input on this issue.

The [CDR Register](https://cdr-register.github.io/register/#cache-refresh-metadata-request) design will not support Data Holder Metadata updates in the initial release.

We will consider a future release for this support
