### ISSUE TITLE
Clarify the way how parameters are injected into the URI of the endpoint

### ISSUE THREAD

**Issue by CDR-AMO** [cdr-register/register#46]
All Register APIs have an industry parameter for which is currently specified as 

Parameter | Value
-- | --
industry | BANKING

As an example, getDataRecipients API GET https://api.discovery.cdr.gov.au/cdr-register/v1/{industry}/data-recipients HTTP/1.1

where value of {industry} is replaced by the actual Value. 
In Register documentation e.g. https://cdr-register.github.io/register/#getdatarecipients, it currently states that value of the parameter industry must be BANKING, i.e. in all caps. if we perform a direct substitution, we will get an error.

In the Change Log section of Register documentation, there is a reference to paths needing to be in kebab-case

23/09/2019 | 0.6.0 | Updated Register APIs | Ensured all paths follow kebab-case.

Can you please:
1) Update the parameter tables in the register documentation so tht

Name | In | Type | Required | Description
-- | -- | -- | -- | --
industry | path | string | true | The industry the participant is retrieving data for (Banking, etc)

will say something like

Name | In | Type | Required | Description
-- | -- | -- | -- | --
industry | path | string | true | The industry the participant is retrieving data for (Banking, etc). Note: The value needs to be in kebab-case

2) Clarify that the value returned in softwareProductId (and other Ids) will always be in kebab-case so that the participant can implement something like a kebab-case converter to parse all injected value when they are forming their URI.

**Comment by CDR-Register-Stream** [comment]
It was identified that the enumeration defining industry followed an Uppercase naming convention but this was inconsistent with the usage in CDS. Therefore, as part of the V1.1.0 changes, the industry enum was changed to lowercase, ensuring direct substitution can occur.

**Comment by CDR-Register-Stream** [comment]
Closing as complete
