### ISSUE TITLE
Certificate Revocation

### ISSUE THREAD

**Issue by spikejump** [cdr-register/register#47]
Based on our current understanding, each ADR will hold, at a minimum, a Server certificate and a Client certificate issued from CDR Root/Intermediate CA.  There can be many reasons where the Client certificate may be revoked, e.g. being compromised.

When a DH issues access_token and refresh_token, the client certificate (signature or something) is baked into the access_token and refresh_token to allow DH to verify HoK.

In the event, when a Client certificate is revoked, all access_tokens and refresh_tokens that were issued with the now revoked Client certificate will also become invalid?  Is this correct?  Can this be clarified?

If this is the case, is the ADR meant to inform their customers that their consent ended pre-maturely due to whatever reason and they need to now raise new consents?

What should be the DH's action on their side?  Are they supposed to de-activate all invalid tokens and keep the valid tokens? or just let normal validation to kick-in for each incoming token?

**Comment by CDR-Register-Stream** [comment]
As per the [CDS Transaction Security section](https://consumerdatastandardsaustralia.github.io/standards/#transaction-security) 

> [MTLS] HoK allows issued tokens to be bound to a client certificate as specified in section 3 of [MTLS].

Digging into section 4 of this standard, the following is detailed which describes that access tokens and not refresh tokens are certificate bound:

> 4.4. Certificate Bound Access Tokens
> As described in Section 3, an access token is bound to a specific client certificate, which means that the same certificate must be used for mutual TLS on protected resource access. It also implies that access tokens are invalidated when a client updates the certificate, which can be handled similar to expired access tokens where the client requests a new access token (typically with a refresh token) and retries the protected resource request.

**Comment by perlboy** [comment]
@spikejump usually MTLS binding is done using the certificate thumbprint. It isn't "baked in" to the token but instead recorded side by side with the token during issuance by the IdP.

**Comment by CDR-Register-Stream** [comment]
Closing as clarification has been provided
