### ISSUE TITLE
Revoked Inactive ADR and Software Product Status

### ISSUE THREAD

**Issue by NationalAustraliaBank** [cdr-register/register#48]
During the ACCC DSB CDR Technical Register Workshop held on the 29th of November a point was raised that the cascading status for a Revoked ADR should be Removed rather than Inactive. The rationale for this being that the certificates have been revoked, all consents have been expired and there seems little value in being able to reactivate the software product as opposed to re-registering with the Data Holder. NAB's position is that it is a simpler solution as we are able to handle the software product client based on the software product status alone. 

In addition the current process for an ADR to be reactivated (documented here https://cdr-register.github.io/register/?#adr-status-changes) appear to have some gaps/inconsistencies.

ADR Reactived
- Client Certificates have been revoked, but no step to reissue certificates

ADR Revoked
- Point 2 mentions all associated software products will be updated to "Revoked".

We request that this issue be addressed by the Registry.

**Comment by CDR-Register-Stream** [comment]
This issue is currently on our radar and we will provide guidance once we have validated/invalidated this state change

**Comment by CDR-Register-Stream** [comment]
@NationalAustraliaBank Thank's for your patience on this issue.
We agree with your feedback that the state ADR Revoked and SP Inactive is an invalid state and therefore the [Data Holder Responsibilities section](https://cdr-register.github.io/register/#data-holder-responsibilities) and [Status Mapping Cascade](https://cdr-register.github.io/register/#accredited-data-recipient-and-software-product-statuses) rules are inaccurate.

We have further work to do to coordinate this change but we will document this on this thread

**Comment by anzbankau** [comment]
ANZ supports this proposed change.

**Comment by CDR-Register-Stream** [comment]
This has now been resolved and documented in release 1.1.1.

Closing as complete

**Comment by cdradr** [comment]
Suggestion: would it be possible to mention in the issue what is the actual resolution? May be copy and paste from the standard? It would be more productive for everyone and also this helps people that find this ticket months or years later...

**Comment by CDR-Register-Stream** [comment]
@cdradr thank you for your suggestion.

For reference, the ADR Revoked and SP Inactive states have been removed from the [DH responsibilities matrix](https://cdr-register.github.io/register/#data-holder-responsibilities), removing the requirement for DHs to handle this state change
