### ISSUE TITLE
Admin endpoint

### ISSUE THREAD

**Issue by Mekaal** [cdr-register/register#51]
In the DH schema there is no admin endpoint in endpoint details section (although it is listed in the Participants Endpoints section within "Transaction Security").  Is this an oversight?  Can it be confirmed that this is stored at the data holder brand level?

**Comment by CDR-Register-Stream** [comment]
Data Holders are required to provide their AdminBaseUri as part of Register onboarding. However, the Register is the only party which will call the Admin Endpoints. Therefore, the Admin Endpoint is not exposed in the GetDataHolderBrands API call

**Comment by CDR-Register-Stream** [comment]
Closing as response provided
