### ISSUE TITLE
Adopt sector_identifier_uri support for Pairwise Pseudonym Identifier (PPD) calculations

### ISSUE THREAD

**Issue by CDR-Register-Stream** [cdr-register/register#52]
The CDR Register design is targeting a future release to support the sector_identifier_uri support for Pairwise Pseudonym Identifier (PPD) calculations.

Please refer to #39 for previous analysis

This issue has been raised to help track and coordinate with the wider community

**Comment by CDR-Register-Stream** [comment]
This issue is currently associated with Project 1.3, targeting completion by November 2020.

We are seeking feedback from the community on where this issue sits in terms of priority and the potential impact for deferring addressing this until 2021.

Feedback has been requested in this and other forums and will be considered until 1st August 2020

**Comment by perlboy** [comment]
The use of `sector_identifier_uri` is a clear recommendation by the upstream specification. There is no reason why it should not be supported as soon as possible.

**Comment by WestpacOpenBanking** [comment]
We are supportive of the introduction of `sector_identifier_uri` support for Pairwise Pseudonym Identifier calculations. Build effort would be required for us to support this proposed change. For this reason we recommend that changes are aligned with a post-March register release.

**Comment by CDR-Register-Stream** [comment]
We are extending the request for feedback until **6th September** to give collaborators greater opportunity to contribute

**Comment by spikejump** [comment]
Back in #39 it was already determined there's a need for the `sector_identifier_uri`, although not on day 1.  That was back in Feb 2020.  Agree with @perlboy that it should be supported as soon as possible.

**Comment by NationalAustraliaBank** [comment]
NAB supports the post above by @WestpacOpenBanking

**Comment by CDR-Register-Stream** [comment]
This issue has been targeted for the July 2021 release since September 2020. Any additional feedback will be considered until  15th November 2020

**Comment by CDR-Register-Stream** [comment]
`sector_identifier_uri` has now been added as an optional field in the SSA.

Please refer to the [Client Registration](https://cdr-register.github.io/register/#dynamic-client-registration) section of the CDR Register design for details

Closing as issue now addressed in V1.3.0 of the CDR Register design
