### ISSUE TITLE
KID value in the JWKS

### ISSUE THREAD

**Issue by SachiniSiriwardene** [cdr-register/register#56]
How is the value for the KID computed in the JWKS? Is there any standard that should be followed?
Need to clarify this since the kid value is needed to obtain the TLS certificate in order to bind it to the token. (Holder of Key)

**Comment by SachiniSiriwardene** [comment]
Any update on this?

**Comment by CDR-Register-Stream** [comment]
@SachiniSiriwardene. The JWKS is specified in RFC 7517 with the Key ID specified in [section 4.5](https://tools.ietf.org/html/rfc7517#section-4.5).
I'll point you to the phrase:

> The structure of the "kid" value is unspecified.

The CDR Register design does not prescribe the structure but for reference, the JWKs exposed by the CDR Register uses UUIDs to represent the `kid` and can been seen in the following [example](https://cdr-register.github.io/register/#dynamic-client-registration)


Do you want to elaborate on the second part of your request?

> Need to clarify this since the kid value is needed to obtain the TLS certificate in order to bind it to the token. (Holder of Key)

**Comment by SachiniSiriwardene** [comment]
In the CDS, it is mentioned that the transport certificate should be bound to the access token.
It is mentioned in the [https://consumerdatastandardsaustralia.github.io/standards/#transaction-security] under the holder of key section.
When binding the TLS certificate to the access token, since the certificates need to be retrieved form the jwks endpoint, there should be a mechanism to select the correct certificate. 
For that purpose need a method to retrieve the kid.
For example, in the UK open banking specification, the kid value is mentioned as the "SHA-1 hash of the JWK Fingerprint"
Without calculating the kid value, there is no mechanism to retrieve the transport certificate from the jwks endpoint.

**Comment by SachiniSiriwardene** [comment]
I really appreciate any feedback on this concern.

**Comment by CDR-Register-Stream** [comment]
@SachiniSiriwardene Thank you for your patience. This issue is on my radar and I plan to have a response for you imminently

**Comment by CDR-Register-Stream** [comment]
For interactions with the CDR Register's authenticated endpoints, access tokens must be provided which have been issued applying the holder of key mechanism. 

These access tokens are bound to the client CA issued transport certificate, used when authenticating with the token endpoint, secured with MTLS. Self-signed certificates are not used in the holder of key checks.

This follows the specification described in the Consumer Data Standards. For further details, I recommend you raise an issue on the [CDS maintenance repository](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues)

**Comment by perlboy** [comment]
Just highlighting here that [MTLS] within the Register docs refers to Mutual TLS (although the normative reference is never provided) while [MTLS] in the CDS refers to [OAuth 2.0 Mutual-TLS Client Authentication and Certificate-Bound Access Tokens](https://tools.ietf.org/html/rfc8705). Perhaps this is the source of confusion?

**Comment by CDR-Register-Stream** [comment]
This discussion has moved to the [CDS Standards Maintenance Repository](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/183) so I will close.

@perlboy I note that reference to the normative references is outstanding and should be specified
