### ISSUE TITLE
aud claim inconsistency between description and example

### ISSUE THREAD

**Issue by CDR-Register-Stream** [cdr-register/register#58]
It has been raised that the `aud` claim as described in [Registration Requests using JWT](https://cdr-register.github.io/register/#registration-request-using-jwt) is unclear as the description  states `Data Holder auth server URI` while the non-normative example shows the base uri.

Coupled with this, confusion exists as the `aud` claim is described in Consumer Data Standards for [Client Authentication](https://consumerdatastandardsaustralia.github.io/standards/#client-authentication) and [Request Object](https://consumerdatastandardsaustralia.github.io/standards/#request-object) and has been discussed at length [here](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/53)

These a different scenarios and should not be confused with the DCR Request.

The intent of the design has been to follow the non-normative example provided by [UK Open Banking](https://openbanking.atlassian.net/wiki/spaces/DZ/pages/36667724/The+OpenBanking+OpenID+Dynamic+Client+Registration+Specification+-+v1.0.0-rc2) and currently there is no motivation to deviate from this

~To clear up confusion and to ensure the description matches the non-normative example, the description of the aud claim will be updated to: `Data Holder Auth Server Base URI`~

_Based on the feedback provided, the documentation will be updated to dictate that the aud value must be populated with the issuer value as described in the OIDC Discovery Document_

**Comment by anzbankau** [comment]
ANZ would preference keeping the current standards and allowing data holders to choose whether the audience is populated with the base URL or full path (based on the issuer returned in the response from OIDC well-known).
There will be implementation impacts if change is required.

**Comment by mt-aanwar** [comment]
To eliminate potential different interpretation by different participants, may I advise for the upcoming update on the standard be more specific on what would be considered as `Data Holder Auth Server Base URI` and how this value could be consistently extracted from data holder's endpoint information in either response of get data holder brands (https://cdr-register.github.io/register/#getdataholderbrands) or response of data holder's OIDC discovery endpoint?

Using the following as an example, could the standard be specific on what would be the base URI given the following auth server URI `https://host/subpath1/subpath2/subpath3/...`?

**Comment by brett-frollo** [comment]
We agree with Alvin's comment. From a Data Recipient point of view we don't mind how the `aud` claim is determined, as long as it is determined in the same way for each current and future Data Holder. We want to avoid having to do different things for different Data Holders.

**Comment by cdradr** [comment]
+1 for standard way to compile aud claim for all data holders.

Should it just be the full URL of the endpoint request object is posted to?

**Comment by spikejump** [comment]
+1 on @mt-aanwar  and @brett-frollo 

If will be great if the standard can be specific on how 'aud' value can be systematically derived with the information Data Recipients have access to.  Simply stating `Data Holder Auth Server Base URI` can still leads to confusion.

**Comment by CDR-Register-Stream** [comment]
Thank you all for your input both online and offline.
Resolution of this issue is intended to provide explicit clarity on how to populate the `aud` value.

Based on the feedback provided, the documentation will be updated to dictate that the `aud` value must be populated with the `issuer` value as described in the [OIDC Discovery Document](https://consumerdatastandardsaustralia.github.io/standards/#end-points)

**Comment by CDR-Register-Stream** [comment]
This issue has now been resolved and documented in release 1.1.1.

Closing as complete
