### ISSUE TITLE
iat claim example is a String?

### ISSUE THREAD

**Issue by perlboy** [cdr-register/register#61]
Minor but important the `iat` claim specified in the sample `POST /register` call is quoted `"1571808167"`. I assume this is meant to be an integer (as per the claim spec) and so should therefore simply be `1571808167`?

**Comment by CDR-Register-Stream** [comment]
@perlboy Thank you for raising this issue.

For reference, here is [RFC 7519](https://tools.ietf.org/html/rfc7519#page-10) specification.

The swagger definition will be updated to correct this

**Comment by CDR-Register-Stream** [comment]
For reference, the non-normative example has been updated accordingly. No update was required in the swagger definition.

This issue has now been resolved and documented in release 1.1.1.

Closing as complete
