### ISSUE TITLE
Typo in RegisterDataRecipient

### ISSUE THREAD

**Issue by perlboy** [cdr-register/register#62]
This description looks like a typo:
![image](https://user-images.githubusercontent.com/4291448/75243042-4ef20080-581d-11ea-9d81-b777a287340c.png)

**Comment by CDR-Register-Stream** [comment]
@perlboy Thank you for raising this issue.
Yes this looks like a copy and paste error.

Will update the swagger definition accordingly

**Comment by CDR-Register-Stream** [comment]
@perlboy This typo has now been addressed in the swagger:

dataRecipientBrands | [DataRecipientBrandMetaData] | false | none | [Metadata related to Data Recipient Brand]
-- | -- | -- | -- | --


This has now been resolved and documented in release 1.1.1.

Closing as complete
