### ISSUE TITLE
ANZSIC Industry Code Format

### ISSUE THREAD

**Issue by perlboy** [cdr-register/register#63]
Could guidance be given regarding the format of the ANZSIC `industryCode` used in LegalEntity:
![image](https://user-images.githubusercontent.com/4291448/75244081-308d0480-581f-11ea-896c-07785bd23394.png)

Is this the raw ANZSIC number or the text value of the ANZSIC number? The example simply states `"string"`.

**Comment by CDR-Register-Stream** [comment]
@perlboy Thanks for your query.
The industryCode field is intended to be aligned to that specified in the [CommonOrganisation ](https://consumerdatastandardsaustralia.github.io/standards/#tocScommonorganisation)schema in the CDS.

Is the issue you have raised in [CDS standards maintenance #31](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/31) reflective of the same question?

**Comment by perlboy** [comment]
@CDR-Register-Stream Umm, "somewhat" I guess, I'm not sure anymore because:

1. Requests for guidance about what the format is have been unanswered or conversations terminated
2. Requests for guidance about decisions regarding zero padded numbers have resulted in multiple ambiguous answers
3. There are zero examples of payloads from ACCC or the DSB that demonstrate this code so it may be a text field
4. It's been 6 months since I asked the question in CDS and 3 months since I asked the question here

Since participant testing has the transparency of a muddy pond it's impossible to determine whether Recipients, Holders, ACCC, EY et al. have coalesced around any answer at all.

What I would note is that "alignment" is a nice word but it is called `LegalEntity` in Register Spec and `CommonOrganisation` in CDR Spec. Consequently for Biza they are described as two [separate](https://github.com/bizaio/babelfish/blob/master/src/main/java/io/biza/babelfish/cdr/models/payloads/common/CommonOrganisationV1.java) [objects](https://github.com/bizaio/babelfish/blob/develop/babelfish-cdr/src/main/java/io/biza/babelfish/cdr/models/payloads/register/common/LegalEntityDetail.java) in Babelfish albeit as String's with absolutely no validation in the absence of any guidance.

**Comment by perlboy** [comment]
_Preamble: Biza currently has 16 open issues on CDR Register (and had until cleanup 42 on CDSA Standards). In an effort to optimise our own backlog we are closing those which have none or limited response from the ACCC. They may be reopened at a later time or referenced when the issues are highlighted by third parties._

Neither party appears to have provided guidance on this, Babelfish performs no validation on ANZSIC from either specification.
