### ISSUE TITLE
GetSoftwareStatementAssertion Access Control

### ISSUE THREAD

**Issue by perlboy** [cdr-register/register#65]
It isn't explicitly specified although a 403 Error Response is provided but for `GetSoftwareStatementAssertion` is this endpoint limited to the SSA's the supplied token has access to?

**Comment by CDR-Register-Stream** [comment]
@perlboy Thanks for your query. 

Yes this is correct. The [dataRecipientBrandId](https://cdr-register.github.io/register/#getsoftwarestatementassertion-ssa) in the path is checked against the issued access token. A 403 is returned if these do not match

**Comment by perlboy** [comment]
Thanks, closing.
