### ISSUE TITLE
Data Holder Logo Location

### ISSUE THREAD

**Issue by perlboy** [cdr-register/register#66]
The definition for `RegisterDataHolderBrand` does not appear to include a `logoUri` like Recipients? As part of the CX flow there is a requirement to present Holder's logo's. There's a fair bit of commentary for logo's related to Recipients but doesn't appear to be any for Holders.

Is a `logoUri` for Holders somewhere in the payloads?

**Comment by pcurtisrab** [comment]
Regional Australia Bank echoes the concerns of @perlboy.

Specifically, logos appear to be mandatory if not at least available according to the [CX Guidelines](https://consumerdatastandards.org.au/wp-content/uploads/2020/01/CX-Guidelines-v1.2.0-1.pdf) (c.f. pp 65-69)

We would suggest simply including "logoUri" as a required string in the [RegisterDataHolderBrandServiceEndpoint schema](https://cdr-register.github.io/register/#tocSregisterdataholderbrandserviceendpoint)

**Comment by acccivan** [comment]
@perlboy @pcurtisrab Thanks for raising this issue. This is a known issue and I'll update this thread once it has been resolved.

**Comment by CDR-Register-Stream** [comment]
This issue has now been resolved and documented in release 1.1.1.

Closing as complete

**Comment by CDR-Register-Stream** [comment]
For reference, the following changes were made:

* RegisterDataHolderBrand: logoUri added
* LegalEntityDetail: logoUri added
