### ISSUE TITLE
Expected Behaviour of Multiple Data Holder Auth Details

### ISSUE THREAD

**Issue by perlboy** [cdr-register/register#67]
`RegisterDataHolderBrand` documents that `RegisterDataHolderAuth` is an array of entries. Is this is an exclusive OR based on `registerUType`? Ie. Is it possible to have multiple JWKS endpoints specified for a specific type of auth (at this point just `HYBRIDFLOW-JWKS`)? 

In addition, under what circumstances is this information used, a few options of what this might potentially mean:
  1) This seems to be setup to allow Data Holders to make authenticated calls to Data Recipients? 
  2) This entire structure is deprecated following the adoption of Dynamic Registration (where JWKS details would be dynamically discovered)?
  3) This structure is used by the Register to sign requests to Data Holders?

**Comment by CDR-Register-Stream** [comment]
@perlboy Thank you for your query.

Reference to #81 that `HYBRIDFLOW-JWKS` has now been renamed to `SIGNED-JWT`

The design for the Data Holder Auth Details structure was inherited from the previous design. The approach was that there may in the future be additional auth mechanisms which occur in parallel to stagger deprecation. To provide the flexibility for change, it was decided that this structure is an array.
There will be only one type of registerUType entry in this array.

I'll answer your remaining questions individually
1. This is correct
2. The intent of this structure is to allow segregation of the JWKS being used as part of the OIDC Discovery process and the DH -> ADR client authentication mechanism. This provides the flexibility for DHs to use a different JWKS endpoint for different use cases. It may be the case that the DH build two independent systems and chooses not to couple them at the secrets store. Of course this is optional, the DH may use one set of JWKS for all use cases and therefore duplicate the configuration
3. No. This structure does not cater for the Register calling out to Data Holders

**Comment by perlboy** [comment]
Hi @CDR-Register-Stream thanks for your response. I'll close this now but specifically related to (2) it is an incorrect assumption to assume that the secrets store is coupled if the JWKS endpoint is merged. JWKS are public keys and are typically published on a CDN. The approach taken is highly proprietary in nature when, at a bare minimum, the URI provided could have been a location from which to obtain a discovery document which would itself link to the appropriate jwks. At least then OIDC discovery norms could be followed.

**Comment by CDR-Register-Stream** [comment]
@perlboy Thanks for your input.

For reference, I have raised issue #118 to revisit the segregation of the JWKS endpoints.
We will track there and consider this issue closed for tracking purposes
