### ISSUE TITLE
Required Scopes for API Calls

### ISSUE THREAD

**Issue by perlboy** [cdr-register/register#68]
The scopes required for API access to the Register do not appear to be defined. Can they please be documented so that implementers can ensure the tokens issued by Register contain the scopes they require?

**Comment by CDR-Register-Stream** [comment]
@perlboy Thanks for raising this issue.

This has now been resolved and documented in release 1.1.1.

Closing as complete

**Comment by cdradr** [comment]
For the data recipients calling the register.. should the scope for getting data holder brands be different from getting SSA? Also the scopes can be more generic (not just banking *:bank:*), especially for the SSA call..

**Comment by CDR-Register-Stream** [comment]
@cdradr Thankyou for raising this question. I have created a dedicated ticket #96 for it so that this project can be closed off
