### ISSUE TITLE
x-v header in response

### ISSUE THREAD

**Issue by perlboy** [cdr-register/register#69]
All endpoints include a `x-v` header which appears to be aligned with the Standards in use however none of the responses appear to include an `x-v` header communicating the version returned. Is this intentional? Is a consumer of Register APIs expected to blindly assume that the supplied version is the one requested?

**Comment by CDR-Register-Stream** [comment]
@perlboy Thanks for your query. Lets try to avoid blind assumptions.

Returned `x-v` headers are not specified in the swagger and this needs to be addressed. The intent of the CDR Register is to return the `x-v` header, communicating the version returned

For reference, the `x-v` header is specified in the CDS in the [response headers section](https://consumerdatastandardsaustralia.github.io/standards/#http-headers)

**Comment by perlboy** [comment]
@CDR-Register-Stream I'd prefer to avoid such things as well. The swagger is not the only place this is missing, the [Register APIs](https://cdr-register.github.io/register/#base-urls) documentation specifies all `x-v` values at not mandatory.

Somewhat related  are we to assume that all Response* are structured the same way as with the Standards? That is to say that all responses will include `x-v` headers and `meta` and `links` attributes in the container? This response is specified within the [Standards Payload Conventions](https://consumerdatastandardsaustralia.github.io/standards/#payload-conventions).

This seems like an important issue to resolve quickly because [GetSoftwareProductsStatus](https://cdr-register.github.io/register/#getsoftwarestatementassertion-ssa) for instance does not appear to be a containerised response. With builds going on now there is a reasonably high risk this non-conformance will be permanent.

**Comment by perlboy** [comment]
_Preamble: Biza currently has 16 open issues on CDR Register (and had until cleanup 42 on CDSA Standards). In an effort to optimise our own backlog we are closing those which have none or limited response from the ACCC. They may be reopened at a later time or referenced when the issues are highlighted by third parties._

Leaving this ticket open on the basis documentation is scheduled for update. [Thumb](https://github.com/bizaio/thumb/blob/master/thumb-client/src/main/java/io/biza/thumb/util/HttpUtil.java) uses a unified response content parser and Babelfish for handling responses, consequently responses which are missing `x-v` will attempt to be parsed using the latest available version within [Babelfish](https://github.com/bizaio/babelfish).

**Comment by CDR-Register-Stream** [comment]
V1.2.0 of the documentation and Swagger definitions have now been updated to capture the x-v header in the response.

Work on aligning the Register APIs with the CDS payload conventions will be tracked as part of issue #122 

Closing this issue as complete
