### ISSUE TITLE
Pagination inconsistency

### ISSUE THREAD

**Issue by perlboy** [cdr-register/register#70]
Pagination for Register APIs appears to attempt to follow the Standards for pagination but is only implemented for GetDataHolders. Is there a reason that probably the smallest result set is the only one implementing pagination?

**Comment by Kauabunga** [comment]
With the `updated-since` also missing in these API, When the Metadata Cache attempt to refresh it will be forced to query the entire set of data to be synced rather than the date ranged subset.

Here is a list of all the registry APIs and their pagination support

```
[PAGINATION EXISTS ] https://cdr-register.github.io/register/#getdataholderbrands
[PAGINATION N/A    ] https://cdr-register.github.io/register/#getsoftwarestatementassertion-ssa
[PAGINATION MISSING] https://cdr-register.github.io/register/#getsoftwareproductsstatus
[PAGINATION MISSING] https://cdr-register.github.io/register/#getdatarecipientsstatus
[PAGINATION MISSING] https://cdr-register.github.io/register/#getdatarecipients
```

**Comment by SlatsFR** [comment]
I'd like to follow-up on @perlboy 's and @Kauabunga 's comments. 

Has there been consideration to aligning the getsoftwareproductsstatus, getsoftwareproductsstatus and getsoftwareproductsstatus pagination specification with those outlined in getsoftwareproductsstatus? I suggest this would be a reasonable approach.

Either way - it would be useful to have confirmation the strategy to allow everyone to be confident they will not be required to modify code down the track.

**Comment by perlboy** [comment]
Repasting comment from https://github.com/cdr-register/register/issues/69

> @CDR-Register-Stream I'd prefer to avoid such things as well. The swagger is not the only place this is missing, the Register APIs documentation specifies all x-v values at not mandatory.
> 
> Somewhat related are we to assume that all Response* are structured the same way as with the Standards? That is to say that all responses will include x-v headers and meta and links attributes in the container? This response is specified within the Standards Payload Conventions.
> 
> This seems like an important issue to resolve quickly because GetSoftwareProductsStatus for instance does not appear to be a containerised response. With builds going on now there is a reasonably high risk this non-conformance will be permanent.

**Comment by perlboy** [comment]
_Preamble: Biza currently has 16 open issues on CDR Register (and had until cleanup 42 on CDSA Standards). In an effort to optimise our own backlog we are closing those which have none or limited response from the ACCC. They may be reopened at a later time or referenced when the issues are highlighted by third parties._

There's no response from ACCC on this and it has been open since February. Closing.
