### ISSUE TITLE
Register JWKS Endpoint

### ISSUE THREAD

**Issue by perlboy** [cdr-register/register#72]
The documentation states:
>CDR Register SSA Signing
>  - SSAs will be signed by the Register
>  - Register public keys will be exposed on a dedicated **JWKS URI endpoint**
>  - CDR Register JWKS will be exposed **on an unauthenticated endpoint**, using TLS. This allows for distribution via CDN, increasing tolerance for Register outage
>  - Endpoint details will be provided to participants during the onboarding process

The location of this for the Register is not published, could the documentation please reflect the location of the Register JWKS or is the intention to adopt a security through obscurity approach by not providing the details unless a participant is onboarded?

**Comment by perlboy** [comment]
_Preamble: Biza currently has 16 open issues on CDR Register (and had until cleanup 42 on CDSA Standards). In an effort to optimise our own backlog we are closing those which have none or limited response from the ACCC. They may be reopened at a later time or referenced when the issues are highlighted by third parties._

No response provided, it is assumed that the ACCC believes that security through obscurity is a valid defensive technique. Closing.

**Comment by SongqingGu** [comment]
Team has raised the same question. Can this question be officially answered?

**Comment by CDR-Register-Stream** [comment]
Reopening issue.

This will be addressed as part of the documentation work scheduled for issue #129 

Will keep this issue open to track work to completion

**Comment by perlboy** [comment]
Closing, looks to be resolved.
