### ISSUE TITLE
OAuth 2.0 MTLS Client Auth and Certificate Bound Access Tokens Metadata

### ISSUE THREAD

**Issue by perlboy** [cdr-register/register#74]
[OAuth 2.0 Mutual TLS Client Authentication and Certificate Bound Access Tokens](https://tools.ietf.org/html/draft-ietf-oauth-mtls-17) is specified in the [Standards](https://consumerdatastandardsaustralia.github.io/standards/#transaction-security) as **mandatory** however the [Dynamic Client Registration](https://cdr-register.github.io/register/#dynamic-client-registration) specification within the Register does not include the `mutual_tls_sender_constrained_access_tokens` parameter in the [Registration Request using JWT](https://cdr-register.github.io/register/#registration-request-using-jwt) section.

Consequently, the lack of advertisement of this support by the client should result in it reverting to it's default value of `false` which, by definition should result in all registration requests to a compliant Holder rejecting all registration requests (because it shouldn't accept registrations from clients that **don't** support it).

**Comment by perlboy** [comment]
Further, RFC8705 (which I believe is the ratified version of the linked on) adds 5 (of which 1 and only 1 is to be used) [parameters](https://www.rfc-editor.org/rfc/rfc8705.html#name-client-registration-metadat) to be provided during client registration.

**Comment by perlboy** [comment]
Further on this the [metadata example](https://cdr-register.github.io/register/#register-endpoints) provided in the specification is using the outdated key of `mutual_tls_sender_constrained_access_tokens` which was changed in November 2018 to `tls_client_certificate_bound_access_tokens` and is now ratified under RFC8705.

**Comment by CDR-Register-Stream** [comment]
@perlboy Thanks for highlighting this issue.
We have identified that the usage of `mutual_tls_sender_constrained_access_tokens` is incorrect and will look to update the documentation accordingly.

We will need to respond to you separately regarding the parameters defined in RFC8705

**Comment by perlboy** [comment]
@CDR-Register-Stream you may wish to review https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/146 as well and align with the DSB.

**Comment by anzbankau** [comment]
ANZ supports this proposed change.

**Comment by NationalAustraliaBank** [comment]
NAB believe this is implied in the standards but don't object to this being explicitly defined.

**Comment by CDR-Register-Stream** [comment]
Referencing issue https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/186

**Comment by perlboy** [comment]
This appears to be completed, closing.

**Comment by CDR-Register-Stream** [comment]
For reference, this issue was completed as part of release 1.1.1
