### ISSUE TITLE
Participant logo caching 

### ISSUE THREAD

**Issue by ryderwj** [cdr-register/register#76]
Are there any requirements specified regarding the currency of logo images, other than perhaps honouring a TTL if specified? This question relates to potential caching of logos for participants for both security prescanning and performance reasons.

**Comment by perlboy** [comment]
Somewhat related to this, I haven't found a payload that includes Holder logos at all #66.

**Comment by CDR-Register-Stream** [comment]
@ryderwj Thanks for your query.
At this stage, the Register design will not be mandating logo caching requirements. The participants are providing the urls to the logo endpoints and they can adopt whatever cache control mechanisms they believe are appropriate.

If this is seen to be too unwieldy, I'd be happy to collaborate on this thread

**Comment by CDR-Register-Stream** [comment]
Closing. If there are further discussion points on this topic, please feel free to raise a new issue
