### ISSUE TITLE
RegistrationProperties request_object_signing_alg is optional?

### ISSUE THREAD

**Issue by perlboy** [cdr-register/register#79]
As per the Standards the request object must be present and signed:

> The Request Object is a signed and encoded JWT specified in section 6.1 of [OIDC]. As per [FAPI-RW] section 5.2.2, the request parameter MUST be present on requests to the [OIDC] Hybrid Authorisation End Point. The Request Object enables [OIDC] requests to be passed in a single and self-contained parameter.
> Request Objects MUST be signed by Data Recipients as specified in section 8.6 of [FAPI-RW].

But the `RegistrationProperties` model specifies `request_object_signing_alg` as optional. Is this intended or are clients expected to revert to a default?

**Comment by perlboy** [comment]
_Preamble: Biza currently has 16 open issues on CDR Register (and had until cleanup 42 on CDSA Standards). In an effort to optimise our own backlog we are closing those which have none or limited response from the ACCC. They may be reopened at a later time or referenced when the issues are highlighted by third parties._

No response has been provided. [Thumb](https://github.com/bizaio/thumb) assumes, unless otherwise [provided as a primary preference in the Discovery document of an issuer](https://github.com/bizaio/thumb/blob/0a01a90f3eb06d24adac00274f6050cee4bfa4c6/thumb-client/src/main/java/io/biza/thumb/util/RegistrationUtil.java#L233) the following:

- Signing algorithm used is `PS256`
- Encryption algorithm used is `RSA_OAEP_256`
- Encryption encoding is `A256GCM`

As stated above, if a Holder is advertising any of the relevant fields the first (and therefore preferenced) value will be used during registration and, as a consequency, future operations will be signed/encrypted/encoded with these settings.

Closing ticket.

**Comment by CDR-Register-Stream** [comment]
Reopening as this appears to be a potential defect in the [Registration request](https://cdr-register.github.io/register/#dynamic-client-registration) section of the CDR Register documentation

**Comment by perlboy** [comment]
Still not resolved but can't be bothered anymore see https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/354

**Comment by perlboy** [comment]
Still not resolved and the CTS is now (changed since November) **deliberately** not sending a `request_object_signing_alg` in the registration request.

Consider yourself warned.

**Comment by CDR-Register-Stream** [comment]
Reopening this issue so we can track investigation and potential updates.

Current analysis shows the following:
1. `request_object_signing_alg` is optional however this does not align with the Open Banking UK specification, from whichour design is based on
2. `request_object_signing_alg` appears to be implicitly required as there isn't currently a use case where a registration would be used exclusively to obtain a token without a request object being a pre-requisite somewhere in the sequence
3. `request_object_signing_alg` as optional would make sense if we had a logical default, or gave the data holder the ability to choose an appropriate default however further investigation is required to determine if this is appropriate
4. Current CTS implementation does not incorporate the `request_object_signing_alg` field in the registration request so further updates may be required to align to the design

**Comment by CDR-Register-Stream** [comment]
This change has been included in V1.5.0

Our analysis has resulted in the following:

* `request_object_signing_alg` is a mandatory response value in Registration [POST and PUT flows](https://cdr-register.github.io/register/#registration-flows).
* `request_object_signing_alg` still remains optional in the [Registration Request using JWT](https://cdr-register.github.io/register/#registration-request-using-jwt). 
If an ADR does not choose to use this field in their requests, the data holder would be expected to set an appropriate default value and return this in the response as request object signing is integral to the CDS.


Closing as complete.
