### ISSUE TITLE
RegistrationProperties states required software_roles property missing in definition

### ISSUE THREAD

**Issue by Kauabunga** [cdr-register/register#84]
https://github.com/cdr-register/register/blob/master/includes/swagger/swagger_dcr.json#L201

The required property `software_roles` does not appear in the `RegistrationProperties` definition properties.

**Comment by CDR-Register-Stream** [comment]
@Kauabunga Thanks for your query.

`software_roles` is part of the [SSA definition](https://cdr-register.github.io/register/#dynamic-client-registration), returned by the CDR Register when the GetSoftwareStatementAssertion is successfully called.

This is not part of the [registration request](https://cdr-register.github.io/register/#registration-request-using-jwt), hence it is not included in the swagger definition

**Comment by Kauabunga** [comment]
Hi @CDR-Register-Stream

So it needs to be removed from the **required properties** of the RegistrationProperties definition? That is where my confusion is.

```javascript
RegistrationProperties: {
   type: "object",
   required: [
     ...
     "software_roles", // Not part of RegistrationProperties properties
     ...
   ],
...
```

See in dcr swagger specification @ https://github.com/cdr-register/register/blob/master/includes/swagger/swagger_dcr.json#L201

**Comment by CDR-Register-Stream** [comment]
`software_roles` is missing from the Register response. This is a bug as the swagger definition deviates from the design as described in [Registration Responses](https://cdr-register.github.io/register-staging/index.html#registration-response).

> As per [Section 3.2.1](https://tools.ietf.org/html/rfc7591#section-3.2.1) of [RFC7591], additionally, the authorisation server MUST return all registered metadata about this client, including any fields provisioned by the authorisation server itself

**Comment by CDR-Register-Stream** [comment]
The [DCR Swagger definition](https://cdr-register.github.io/register/#dcr-api) will be updated with these properties.

Impact analysis will be performed to determine the impact to participants and manage this change

**Comment by CDR-Register-Stream** [comment]
`software_roles` does not map to any explicit use case and not all data holders are currently persisting this value and returning it in the DCR response.

Introduction of this field as optional will not result in a breaking a change and ensures the DCR swagger specification aligns to the design.

**Comment by CDR-Register-Stream** [comment]
V1.5.0 introduces `software_roles` to the DCR_API swagger as an optional field in the Registration Properties.
This should have no impact to data holders who have not chosen to persist this value.

Closing as complete.
