### ISSUE TITLE
LegalEntityDetail registered country is flagged as required even though it is for foreign entities

### ISSUE THREAD

**Issue by CDR-Register-Stream** [cdr-register/register#85]
[LegalEntityDetail](https://cdr-register.github.io/register/#tocSlegalentitydetail) field registeredCountry is a required field but is only relevant for foreign entities.

This field should be flagged as optional to be consistent with the other fields: 
* registrationNumber
* registrationDate

**Comment by NationalAustraliaBank** [comment]
NAB do not see an issue with this proposal

**Comment by CDR-Register-Stream** [comment]
This has now been resolved and documented in release 1.1.1.

Closing as complete
