### ISSUE TITLE
Certificate requirements for ADRs needs to be updated based on changed MTLS requirements

### ISSUE THREAD

**Issue by CDR-Register-Stream** [cdr-register/register#86]
Consumer Data Standards was updated to remove the requirement of MTLS for ADR revocation endpoint which has also removed the requirement to use an ACCC issued certificate.

The following changes need to be made in the Certificate Management section:

**Issued by ACCC CA for Accredited Data Recipients**
Secures the following:
- InfoSec endpoints **changed to** Revocation Endpoint

Remove the following text:
_ADRs will be required to secure their Revocation Endpoint with an
ACCC CA issued certificate_

**Comment by CDR-AMO** [comment]
It is better to change the text to "ADRs may secure their Revocation Endpoint with an
ACCC CA issued certificate or a certificate issued by a public CA", if you want to leave it up to the participant on what certificate they want to use. Removing the text might cause some participants to start rejecting ACCC CA issued certificate

**Comment by perlboy** [comment]
If an ADR chooses to use a public certificate how does a Holder establish cryptographic verification they are actually talking to the ADR?

**Comment by CDR-Register-Stream** [comment]
This issue has now been resolved and documented in release 1.1.1.

@perlboy Thankyou for your query. Can you please raise this question in the standards-maintenance repository? Otherwise it won't get the appropriate eyes on it

**Comment by perlboy** [comment]
@CDR-Register-Stream Not really because the updated statement indicates that the ACCC is ok with the use of a public certificate despite it being in a section that specifically talks about it being an ACCC CA issued certificate...
