### ISSUE TITLE
Register swagger does not define error code 406 for requests with an invalid x-v header

### ISSUE THREAD

**Issue by CDR-Register-Stream** [cdr-register/register#91]
The [Consumer Data Standards](https://consumerdatastandardsaustralia.github.io/standards/#http-headers) specifies an error code of 406 is returned when invalid `x-v` or `x-min-v` headers are provided

The Register swagger definition does not define error code 406 for these scenarios. Register APIs are to conform to the CDS convention so for clarity, these error codes should be specified

**Comment by perlboy** [comment]
Is this related to #69 ?

**Comment by CDR-Register-Stream** [comment]
@perlboy Issue #69 you have raised is a separate issue and we will track it in the issue you've raised.
This issue is about ensuring that 406 is specified in the swagger definition.

This has now been resolved and documented in release 1.1.1.

Closing as complete
