### ISSUE TITLE
Feedback 94: DH Consumer Dashboard useful fields

### ISSUE THREAD

**Issue by CDR-Register-Stream** [cdr-register/register#94]
The [GetDataRecipients ](https://cdr-register.github.io/register/#getdatarecipients) API is optimised for the use case for Data Holders presenting Consumer Consent dashboards. However, it is noted that there would be benefits having additional fields both to support CX recommendations and allow for innovation.

The ACCC would like to ask Data Holders and the community if there are any other fields they feel would be beneficial for this use case.

Currently the only additional item we have in our list is:
* The accreditation number for the ADR to support CX recommendations

**Comment by CDR-Register-Stream** [comment]
For release **1.2.0**, this work will be constrained to exposing the human readable accreditation number for the ADR to support CX recommendations

**Comment by perlboy** [comment]
Suggest there's an option to use an identicon for accrediation details. Accreditation numbers alone are easily forged and provide no correlation to a specific agreement/registration. Identicons would allow a holder to combine a a combination of attributes on their side with the unique identifier of the recipient. On this basis a holder could publish a unique set of identicons (within their help pages for instance) that would correlate specifically for an individual holder to recipient. They could then link this resource to an appropriate accreditation detail at the ACCC register.

**Comment by CDR-Register-Stream** [comment]
V1.2.0 now reflects the addition of the new accreditationNumber for the GetDataRecipientsAPI

Further consideration for identicons is captured in issue #123 

Closing this issue as complete
