### ISSUE TITLE
x-v header is not specified in the DCR Swagger definitions

### ISSUE THREAD

**Issue by CDR-Register-Stream** [cdr-register/register#95]
The [DCR Swagger](https://cdr-register.github.io/register/includes/swagger/swagger_dcr.yaml) definitions do not specify the requirement for **x-v headers** which doesn't align to the Consumer Data Standards [HTTP header requirements](https://consumerdatastandardsaustralia.github.io/standards/#http-headers).

**Comment by perlboy** [comment]
`x-v` headers within CDR Register API's makes sense however `x-v` headers within DCR API's does not. 

The Register documentation specifies the following with regards to DCR: `The CDR Registration model follows standard [RFC7591] and is derived from Open Banking UK model with design input from the ABA`. Neither of these Standards utilises a versioning header instead relying on capability advertising as per OAuth2 approach. 

Is the ACCC now proposing to create a new standard for dynamic registration that uses polymorphic version responses? If so this has significant implications to the underlying standards which, by and large, give explicit guidance around what to do with attributes that are not understood (usually ignored or cause request rejection depending on the type of call). Does the ACCC intend to perform security evaluation of this modification to internationally recognised and hardened specifications?

**Comment by anzbankau** [comment]
ANZ does not support the use of x-v header for the DCR and Security profile end points. We agree with @perlboy in regards to not deviating from the base standards in this regard.

**Comment by spikejump** [comment]
+1 for @perlboy and @anzbankau

**Comment by CDR-Register-Stream** [comment]
@perlboy, @anzbankau, @spikejump. Thank you for your feedback. 

Based on your feedback and review of the upstream standards, we see no reason to align with the CDS versioning model for DCR endpoints.
